### ISSUE TITLE
Access Violation when calling LoadFromString

### ISSUE THREAD

**Issue by PopRe** [BerndGabriel/HtmlViewer#100]
The function "LoadFromString" is called with a string and the following access violation was reported:
```
exception class    : EAccessViolation
exception message  : Access violation at address 00408F08 in module 'Program.exe'. Read of address FFFFFFFD.
00408f08 +008 Program.exe System           15513  +1 TObject.Free
007fd493 +01f Program.exe StyleUn           3014  +2 TStyleList.Clear
008330ff +0eb Program.exe HTMLSubs          7104 +24 ThtDocument.Clear
00863cd9 +05d Program.exe HtmlView          4402  +8 THtmlViewer.InitLoad
0085cba9 +1e1 Program.exe HtmlView          1229 +56 THtmlViewer.LoadDocument
0085cf82 +036 Program.exe HtmlView          1297  +3 THtmlViewer.LoadString
0085c9b5 +009 Program.exe HtmlView          1156  +1 THtmlViewer.LoadFromString

**Comment by BerndGabriel** [comment]
Which HtmlViewer Version do you use? 
Which string do you load?

**Comment by PopRe** [comment]
The version was from July 23rd. I don't know the exact string, but it's a simple chat box with coloring for the name and text using CSS so nothing too complicated.  LoadFromString is called every time a new line of chat is added.

**Comment by jsmucr** [comment]
I tried to to replace the old THtmlLite with the new HtmlViewer and started getting this exception too. The first two loads work fine and then it starts crashing in TFreeList.Notify upon freeing a deleted object. I still didn't succeed creating a minimal example though.
