### ISSUE TITLE
Error displaying images

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#101]
I noticed that in earlier versions of the component images are displayed. I can not say what version since they are no longer displayed.
On the old site of the project was the ability to attach files, but not here. Therefore, the example file here: http://rghost.ru/private/8PWw7BRVt/78db4e13c1d0a3447c236873ede467dd

**Comment by SchwarzKopf-M** [comment]
In the version r418 everything displayed normally, but in the version r472 anymore.

**Comment by BerndGabriel** [comment]
Did you try the latest code in this repository? While the released FrameBrowserId10 of 11.6 loads some images only, the FrameBrowserId10 I compiled just now seems to load all images correctly.

Neither FrameBrowserIcs formats the document correctly.

Which Internet components suite do you use?

**Comment by SchwarzKopf-M** [comment]
I used the latest version of the draft code here. THtmlViewer I use the latest version of Indy. In my opinion the problem is not downloading images and display items with images. Displays only the first element with a picture of the entire table.

**Comment by BerndGabriel** [comment]
Commit c4295a431b350441b309495be56acb45c150516a fixes this issue.
