### ISSUE TITLE
GIF transparency inverted + memory leak

### ISSUE THREAD

**Issue by ralfjunker** [BerndGabriel/HtmlViewer#102]
Transparent GIF images are displayed with inverted colors and cause a memory leak.

The problem was introduced by check-in bc29d9765e9be01bf4e7b17cfb34122e3b404011 on 17.06.2015 21:59:15.

To reproduce, open the HTML below with in HtmlDemo.exe so it loads transparent.gif:

```
<html>
<head>
</head>
<body>
<img src=transparent.gif>
</body>
</html>
```

![transparent](https://cloud.githubusercontent.com/assets/1552416/9279298/e2686b46-42b6-11e5-92f1-80bf665d95b8.gif)

To solve, I propose the following patch below against 00056ebe3a15316f9bc617f927f3a2e8d4faf6b2. It works well for me and HtmlViewer\Demos\Compiled Framedemo\sample3.htm shows no obvious side effects.

```
--- a/source/HtmlImages.pas
+++ b/source/HtmlImages.pas
@@ -633,7 +633,7 @@ begin
       if Bitmap <> nil then
       begin
         //if Transparent = LLCorner then
-          Mask := GetImageMask(Bitmap, False, 0);
+          // Yunqa.de removed: Mask := GetImageMask(Bitmap, False, 0);
         Bitmap := ConvertImage(Bitmap);
         Result := ThtBitmapImage.Create(Bitmap, Mask, Transparent);
       end;

--- a/source/HTMLSubs.pas
+++ b/source/HTMLSubs.pas
@@ -2866,7 +2866,7 @@ begin
     H := ObjHeight;
   end;
   try
-    ddImage.Transp := Transparent;
+    // Yunqa removed: ddImage.Transp := Transparent;
     if IsCopy then
       ddImage.Print(Canvas, XX, Y, W, H, clWhite)
     else
```

Ralf

**Comment by BerndGabriel** [comment]
Thanks for investigating this issue. 

Commit 5dcb18290d630b46a205ea55086118c84a57b597 implements your solutions.
