### ISSUE TITLE
Installing Htmlviewer on Delphi XE8

### ISSUE THREAD

**Issue by irelam66** [BerndGabriel/HtmlViewer#104]
I am unable to fully install Htmlviewer version 11 on my Windows 10 64-bit machine. I am able to compile the DPK file after correcting syntax errors on the content of the DPK file. Errors are 
1. Miss-spelling of Requires is supplied with two 'R' at start of the line.
2.                          Contains                                'C'
3. Final end statement appears as 'd'
Correcting these problems and then all the DCU files appear in my DCULIB directory.
But I am then unable to install the component, and there is no sign of the component icon and the Complib build fails.  I remember there was a problem with the Delphi XE starter kit that could not register a component and make it appear in the list of installed components.  Is this still a problem or is this a new version of the problem. FrameviewerReg.pas seems to have the code

**Comment by BerndGabriel** [comment]
Hi, I cannot see any defects in https://github.com/BerndGabriel/HtmlViewer/blob/HtmlViewer-11.6/package/FrameViewerXE8.dpk and I'm not aware of any registration bugs. But I must admit, I've got neither XE nor XE8.

**Comment by irelam66** [comment]
Thank you for your feedback on this problem. I am not so worried about the corrupted DPK 
file as the problem is clear and easily corrected. I am actually more worried that I cannot 
seem to get the component installed and appearing on the component toolbar.  It usually 
requires a routing called RegisterComponent to be run somehow. I cannot find such a routine 
(procedure) anywhere in the XE distribution collection of files.
I am going to investigate running this procedure outside the Install procedure, and will let you 
know of my success or whatever.
The code I am trying to track down looks like this (from Frameviewer.reg in my Html945 set):


    procedure Register;
    begin
       RegisterComponents('Samples', [THTMLViewer, TFrameViewer, TFrameBrowser]); 
    end;


regards,
               Martin
==========================

**Comment by BerndGabriel** [comment]
since Delphi XE there is a separate dclFrameViewerXE*.dpk package for
the design time including the RegisterComponent() call.

Am 05.09.2015 um 02:47 schrieb irelam66:

**Comment by irelam66** [comment]
The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  FrameviewerXE8_dpk.jpg
     Date:  5 Sep 2015, 13:22
     Size:  99449 bytes.
     Type:  JPEG-image

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any other MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- File information -----------
     File:  delphixe8DclFrameviewer_syntaxerrors.jpg
     Date:  5 Sep 2015, 13:17
     Size:  24876 bytes.
     Type:  JPEG-image

**Comment by BerndGabriel** [comment]
Unfortunately you cannot send attachments github issues.

But you can send links to publicly available files.

**Comment by BerndGabriel** [comment]
Issue seems to be solved...
