### ISSUE TITLE
Print Preview Bug

### ISSUE THREAD

**Issue by AlexBuzaev** [BerndGabriel/HtmlViewer#106]
If you open this file www.Frigate3.com/download/html3.Zip in FrameDem.exe, it looks all right. However, if you view it in Print Preview, all images are lost except the first one.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 
commit 318a7822a349de2b8c3bcc32df5079ad9beb66da fixes it in HtmlViewer-11.6
commit 90bbc00e8255984865d5fe8020a987dd21f5c144 fixes it in HtmlViewer-11.6-to-11.7
