### ISSUE TITLE
Packages for Delphi 10 Seattle and updated ICS demo

### ISSUE THREAD

**Issue by magsys** [BerndGabriel/HtmlViewer#108]
I've made changes to support Delphi 10 Seattle and created the packages.

Also made several improvements to the FrameBrowserUsingICSv7 demo to properly support http/1.1, better authentication and form posting.   Sorry, another ICS contributor reformatted some units with the XE2 style formatter which makes merging almost impossible. 

I've used Hithub in the past and found in tedious to submit changes and don't have the time to do so again, so all the changed files are at: 
http://www.magsys.co.uk/download/software/htmlview-11.6-7-magsys.zip

Angus

**Comment by BerndGabriel** [comment]
Thanks for for your support!
I cannot download the zip, as your server returns Code 404 - File or directory not found.

**Comment by magsys** [comment]
Sorry, file is there now.  

Angus

**Comment by BerndGabriel** [comment]
Thanks again.
I updated the ICS demo in branch "HtmlViewer-11.6-to-11.7"
Delphi 10 packages have been committed before as XE9.
