### ISSUE TITLE
Unicode not displayed correctly

### ISSUE THREAD

**Issue by kstan1122** [BerndGabriel/HtmlViewer#109]
Hi, the following are not display correctly:
ā   ṭ   “   ”   ñ
shown as respectively below:
Ä   á¹   â€œ   â€    Ã±

would be great if these problem are solved.

Thanks.

Brad.

**Comment by BerndGabriel** [comment]
Thanks for posting this issue.
Could you please be a bit more specific? 
Which HtmlViewer version do you use?
Which Method do you use to load the document/string?
Which codepage/language is set in your Windows?

Your example looks like the unicode characters are represented in UTF-8. If you load UTF-8 files into a string, you should take care that the loading method does the conversion for you. 

Otherwize you can use THtmlVierwer.LoadFromDocument() with a document constructed by TBuffer.Create(const Text: TBuffString; CodePage: TBuffCodePage; const Name: TBuffString = ''); 
or use class function TBuffer.Convert(const Text: TBuffString; CodePage: TBuffCodePage): TBuffString; to convert the UTF-8 coded text in the unicode string to a real unicode string.
