### ISSUE TITLE
Missing Property AttributeValue

### ISSUE THREAD

**Issue by fs999** [BerndGabriel/HtmlViewer#112]
Hello,
I need some attributes from a form control and there was in version 9.41 the property AttributeValue in TFormControlObj, like this :
TFormControlObj(FormControlList[i]).AttributeValue['style']

Is there a way to access it ?

Thank you
Frederic

**Comment by BerndGabriel** [comment]
Unfortunately property TFormControlObj.AttributeValue[] and its Getter have been commented out in 2013. 

I will reactivate it in the base class THtmlNode as it holds the attribute list now.

**Comment by BerndGabriel** [comment]
Fixed in branches 11.6 and 11.6-to-11.7.

Property AttributeValue[] is back again and now available in all objects derived from THtmlNode (thus including TFormControlObj).
