### ISSUE TITLE
Error displaying

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#113]
In the letters came to me display elements which should not be visible. So file 1.htm display text that does not show any one browser. So the same text is displayed above and below the picture that should not be visible.

Test files: http://rghost.ru/private/7ldXMpQPc/0c30e175fe1807255ffe140b882531ad

**Comment by BerndGabriel** [comment]
These files seem to be intentionally far from HTML syntax.
HtmlViewer will not try to support that.
