### ISSUE TITLE
Error displaying table

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#114]
The text files are not displayed correctly table elements. Sometimes the text is not completely visible. All files in the archive table is not displayed correctly.

Test files: http://rghost.ru/private/6gCzjZPjb/984e3ead39bd477d24069020a348f309

**Comment by SchwarzKopf-M** [comment]
I figured out the problem, it is related to the correction of Issue 411.

**Comment by BerndGabriel** [comment]
samples 11.html - 44.html are looking okay now. 
in sample 55.html there is missing some text. I will look into it later...

**Comment by BerndGabriel** [comment]
The missing text issue in sample 55.html duplicates issue #124
