### ISSUE TITLE
Mail GMail

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#115]
In letters sent to the tablet on Android with mail GMail application has the ability to send smoylikov as symbols. In your browser, the characters are displayed correctly in HtmlViewer displayed as squares. It is possible to do something will support these characters?

Test file: http://rghost.ru/private/6wTXFSgYD/f3b855929f7916d2de7bf727e7805508

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

HtmlViewer does not support unicode characters > 65535. As emoticons start with 128512 they are shown as squares.

HtmlViewer depends on the equality of 1 visible character per Delphi's 16-bit unicode type Char and thus cannot handle 32-bit unicode characters > 65535.
