### ISSUE TITLE
Local Variable initialization

### ISSUE THREAD

**Issue by taazz** [BerndGabriel/HtmlViewer#117]
Please initialize all variables that are passed to events as var so there are no misunderstandings how are suppose to be used. For example the onGetPostRequestEx has various "Var" parameters, it would help if those where initialized to their active value or to an "empty" value (like nil for the memory stream). That will help tremendously with testing and generally exploration of the components.

**Comment by BerndGabriel** [comment]
Did you have problems with a particular event? 
Var-params of OnGetPostRequest/Ex *are* initialized.

**Comment by taazz** [comment]
Oh that was a while back sorry. Yes I had problems with the stream parameter it came out assigned with garbage values. But that was on lazarus not delphi so that might be my problem.

Thank you for your time sorry for the delay answering I did not expected any attention to be frank, that is what I came to expect from open source projects.

**Comment by BerndGabriel** [comment]
If this was an issue it has been fixed in or before 2010.

**Comment by taazz** [comment]
What is 2010? Delphi version?
