### ISSUE TITLE
CSS open parenthesis may swallow entire HTML document

### ISSUE THREAD

**Issue by ralfjunker** [BerndGabriel/HtmlViewer#120]
HtmlViewer displays nothing for this document:

```html
<html>

<head>

<style type="text/css">
p        { counter-increment: p; }
p:before { content: " (" counter(p) " "; }
</style>

</head>

<body>

<p>one
<p>two
<p>three

</body>

</html>
```

Expected output is:

```
(1 one

(2 two

(3 three 
```

The problem is in StylePars.pas, procedure THtmlStyleTagParser.GetCollection. It does not handle quoted strings according to the CSS specification. See http://www.w3.org/TR/CSS21/syndata.html#strings for details.

In particular, note that

* parenthesis do not interfere with string delimiters. Especially, nothing is said that opening and closing parenthesis must match, as HtmlViewer currently requires.
* quotes inside strings may be escaped using \". I do not see that HtmlViewer takes care of this.

Wish: Finally add regression tests to improve stability of HtmlViewer.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit dec4a60c65546c1f2b2492c79a4c2d255fa200da fixes it. 

Please notice that HtmlViewer does not support counter-increment, :before, content and counter.
