### ISSUE TITLE
Error displaying

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#122]
Page is not completely displayed.
http://rghost.ru/private/7K2Xlskwb/0fe471b09212e7a8846cc1e293a531f3

**Comment by BerndGabriel** [comment]
What is wrong with it? 
The missing image at the bottom is OK, as the src does not refer to an image.

**Comment by SchwarzKopf-M** [comment]
When you upgrade to new versions of this problem has been resolved.
