### ISSUE TITLE
File with css from amazon

### ISSUE THREAD

**Issue by FelM** [BerndGabriel/HtmlViewer#123]
Hallo!

I can't load file with css from Amazon E-Mail 
[mail1.txt](https://github.com/BerndGabriel/HtmlViewer/files/73971/mail1.txt)

Best regards,
Felix

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit 6d8390f361427663db8b7413d02069d204759bc0 fixes it.
