### ISSUE TITLE
<table> is not rendered unless scrolled

### ISSUE THREAD

**Issue by adem0x** [BerndGabriel/HtmlViewer#124]
I have come across a weird situation.

In the file (enclosed) there's a table (much simplified from the original source) and it does not contain anything fancy.

Yet, when I try to load it with HtmlDemoW (both from 11.6 and '11.6 to 11.7') it does not get rendered at all (it displays a blank page) unless I scroll the page down. It the shows up. But, if I scroll all the way back up, it disappears again.

As I said, the HTML file is as plain as it gets and renders with any browser without a a hitch.

I couldn't spot where in the source code the problem is; could someone please look into this.

PS: Same problem exists with FrameBrowserUsingICSv7 too.

[tableproblem.zip](https://github.com/BerndGabriel/HtmlViewer/files/76126/tableproblem.zip)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 

Looks like "margin-bottom: -15" is misunderstood.

**Comment by BerndGabriel** [comment]
Hint for solving this issue:
In TBlock.DrawBlock() OpenRgn becomes true because of the negative bottom margin. The clip region manipulations hide the rest of the page until <p> is scrolled off the viewport.

**Comment by adem0x** [comment]
When I modify the code as below:

procedure TBlock.DrawBlock()
  {...}
begin
  {...}
  //NegativeMargins := (MargArray[MarginLeft] < 0) or (MargArray[MarginTop] < 0) or (MargArray[MarginBottom] < 0) or (MargArray[MarginRight] < 0);
  NegativeMargins := False;
  {...}
end;

It works correctly --as far as this problem is concerned.

I know that this cannot be a general solution, but, when I look at the logic of 'NegativeMargins', I am not sure it is the correct approach for a general solution either.

This is what I mean:

Here is the definition for 'CSS boxmodel': http://www.w3schools.com/css/css_boxmodel.asp

Unless I am totally misinterpreting it all, shouldn't we --first--calculate the complete 'boxmodel' for TBlock i.e. 'margins box', 'border box', 'padding box', to arrive at 'content box'?

And, then, if either the width of the height of the 'content box' is zero (or negative, or less than a predefined value), we should skip drawing the TBlock to the screen.

**Comment by BerndGabriel** [comment]
Negative margins allow the content to exceed the content box boundaries, maybe clipped to the padding boundaries: https://www.w3.org/TR/2011/REC-CSS2-20110607/visufx.html
