### ISSUE TITLE
When Scrollbars disapear the table is displayed wrong

### ISSUE THREAD

**Issue by derChristoph** [BerndGabriel/HtmlViewer#125]
I updated from Version   11.4
When the contend dose note fit in the Window the table dose not display corect, as you can see:
![1](https://cloud.githubusercontent.com/assets/13977320/12093448/43f56a78-b303-11e5-8a69-8d03ca956e03.png)
![268 form1 20160104164937](https://cloud.githubusercontent.com/assets/13977320/12093450/46b23fb6-b303-11e5-9900-94e545fb1288.png)

[htmlview.zip](https://github.com/BerndGabriel/HtmlViewer/files/77385/htmlview.zip)
>> scouce & example

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Now fixed in branches HtmlViewer-11.6 and HtmlViewer-11.6-to-11.7.
