### ISSUE TITLE
loading <img hspace vspace>

### ISSUE THREAD

**Issue by trichview** [BerndGabriel/HtmlViewer#126]
img's hspace and vspace are loaded as left and top spacing, while right and bottom spacing remains zeros.
In my test, I have &lt;img width=120 height=72 alt="" hspace=10 vspace=20 src="img44.png"&gt;
After loading, in TFloatingObj,
HSpaceL = 10
HSpaceR = 0
VSpaceT = 20
VSpaceB = 0

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Fixed in Version 11.6 and 11.7
