### ISSUE TITLE
inline in D2006

### ISSUE THREAD

**Issue by Lybster** [BerndGabriel/HtmlViewer#127]
Downloaded the latest 11.6 to 11.7 branch and I had to comment out

  {$ifdef Compiler17_Plus}
    {$ifdef DEBUG}
    {$else}
      {.$define UseInline} <<<<<<<<<<<<<
    {$endif}
  {$endif}

otherwise I get

[Pascal Error] StylePars.pas(306): E2449 Inlined nested routine 'GetTermCharKind' cannot access outer scope variable 'GoodTermChars'
[Pascal Error] StylePars.pas(308): E2449 Inlined nested routine 'GetTermCharKind' cannot access outer scope variable 'BadTermChars'

Apart from that I'm very impressed

**Comment by BerndGabriel** [comment]
Sorry for the inline issue...
