### ISSUE TITLE
NoTabLink is not working

### ISSUE THREAD

**Issue by mgmGK** [BerndGabriel/HtmlViewer#129]
Hi!
When I set NoTabLink. I can't compile anymore because TFrameObj.CreateFrame don't know the TPaintPanel and THtmlViewer :(
I think it is about the ifndef in the HtmlSubs for HtmlView
when I remove this it will compile.
But I don't be sure that this will be okay.
Thanks.

**Comment by mgmGK** [comment]
Problem has disappeared. 
Don't know why.

**Comment by BerndGabriel** [comment]
I can reproduce this issue.
Commit 200f50f31c6c8dbd719430405b3e6fee1f69e4aa fixes it.
