### ISSUE TITLE
IMG tag

### ISSUE THREAD

**Issue by Lybster** [BerndGabriel/HtmlViewer#130]
May be working as designed.

With a tag

<img src="http://www.talentscotland.com/~/media/email-header.jpg?h=260&amp;la=en&amp;w=639" alt="" style="display: block;" />

the OnImageRequest has the SRC parameter set to 

http://www.talentscotland.com/~/media/email-header.jpg?h=260&amp;la=en&amp;w=639

I would have expected it to truncate after the .jpg

**Comment by BerndGabriel** [comment]
Yes, keeping the query part of the URI is intended. It has to be interpreted by the server. Hopefully the server sends an image with the requested properties.
