### ISSUE TITLE
Cell borders in tables / last row wrong

### ISSUE THREAD

**Issue by johnb2007** [BerndGabriel/HtmlViewer#131]
Given the HTML in the attachment (rename txt to htm): IE, FF or Chrome render the tables as expected. But rendered in the FrameDemo.exe, the frames around the cells in the last row of each table are a little bit thinner than in the other cells above the last row. Can you confirm the problem? Do you have a solution for that already? We'd be happy to provide any additional input you may need to look into this.
[html.txt](https://github.com/BerndGabriel/HtmlViewer/files/261052/html.txt)

**Comment by BerndGabriel** [comment]
Additionally to the commitetd fix you must add top lines to the "Gesamt" row. Unfortunately HtmlVIewer does not collapse borders correctly. It is just a quick hack, which simple sets the border-spacing to -1 and as long as all borders have a width of 1 it works well. This way the top resp. left border of a cell overwrites the bottom resp. right border of the cell above resp. to the left.

**Comment by johnb2007** [comment]
Thanks a lot, this is excellent!
