### ISSUE TITLE
Height parameter not honoured

### ISSUE THREAD

**Issue by Lybster** [BerndGabriel/HtmlViewer#132]
[demo.txt](https://github.com/BerndGabriel/HtmlViewer/files/272491/demo.txt)

When a piece of html (from an email) has a line in it like

<div style=
"overflow:hidden;color:transparent;visibility:hidden;mso-hide:all;width:0;font-size:0;opacity:0;height:0;">

the height parameter isn't honoured. What happens is a large gap appears in the displayed email. Its generally at the top.  I think this is the culprit since removing the visibility:hidden parameter shows the text that's there and "pushing" the actual content down.

I don't think the width parameter is honoured either but that's not obvious.

I can delete the block as a workround I think.

The file attached is the html just that I had to alter the extension otherwise I couldn't attach it <G>

**Comment by BerndGabriel** [comment]
Looks like min/max width and height of the div are calculated although visibility is hidden. While drawing the div visibility:hidden or overflow:hidden suppress the text.

**Comment by BerndGabriel** [comment]
Fixed the height handling: Now an explicitly given height is always prefered over the block's content height.
