### ISSUE TITLE
Paragraph alignment regression

### ISSUE THREAD

**Issue by JohnSylver** [BerndGabriel/HtmlViewer#135]
There is a paragraph alignment regression in the version 11.7 - the `<p align="center">` is not centered anymore.
![htmlviewer 11-7 align bug](https://cloud.githubusercontent.com/assets/1853968/15851903/a708033c-2ca7-11e6-8a67-a59ceceeb2eb.jpg)
[HTMLViewer 11-7 align bug.htm.txt](https://github.com/BerndGabriel/HtmlViewer/files/302184/HTMLViewer.11-7.align.bug.htm.txt)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 
Commit https://github.com/BerndGabriel/HtmlViewer/commit/2a7a88a2c8a3a0d59ad98eeca651dddfce305aa1 fixes it.
