### ISSUE TITLE
THtmlViewer.CopyToClipboard not works in Fpc/Lazarus

### ISSUE THREAD

**Issue by MaxTerentiev** [BerndGabriel/HtmlViewer#136]
Hi,

THtmlViewer.CopyToClipboard not works with lazarus. They copy to clipboard something like this:

<O 

Instead of selected html document.

This method works fine in Delphi XE7, problem only with Lazarus.

HtmlViewer 11.6-to-11.7, tested on: Lazarus 1.4.4 + FPC 2.6.4 on Win32/Win64 and Linux64 (CentOS 6), and Lazarus 1.6 + FPC 3.0 on Win32/Win64

**Comment by OldRuby** [comment]
See issue #121 which is similar and offers patches for this

**Comment by BerndGabriel** [comment]
Fixed in master branch
