### ISSUE TITLE
THtmlViewer slow down or hangs Lazarus IDE if Align=alClient

### ISSUE THREAD

**Issue by MaxTerentiev** [BerndGabriel/HtmlViewer#138]
Hi,

HtmlViewer 11.6-to-11.7 slow down (and completely hangs time to time) Lazarus IDE if aligned to alClient. No problems if Align=alNone.

Some times I see this strange behavior: after setting Align=alClient HtmlViewer start growing outside form until IDE crashes ! I mean it's grow up to Width 10000+ / Height 10000+ until IDE craches.

How to reproduce:

1. Place TPanel on form, set Align=alLeft
2. Place TSplitter on form
3. Place THtmlViewer on form, set align=alClient.

IDE may hangs just after setting THtmlViewer.Align. Or this may slow-down form designer, so it's responds very slowly.

No problems if Align=alNone. No problems with Delphi XE7. 

Tested on Lazarus 1.4.4 Win32,Win64,Linux64.

**Comment by BerndGabriel** [comment]
Tested commit 2da4c8289bd1b8d21d28932bb4845a10c6ab4290
with Lazarus 1.4.4, FPC 2.6.4, SVN 49931
and Lazarus 1.6, FPC 3.0.0, SVN 51630
Any further hint how to reproduce the issue is welcome.

**Comment by MaxTerentiev** [comment]
I can't longer reproduce it myself. But probably this issue related to ProcessMessages overloading by THtmlView. I created new Issue about it.

**Comment by BerndGabriel** [comment]
New issue: #142
