### ISSUE TITLE
Line breaks in <pre> are not recognized

### ISSUE THREAD

**Issue by SebastianZ** [BerndGabriel/HtmlViewer#140]
Line breaks within `<pre>` content should be considered. Instead, the whole text is displayed in a single line.

E.g.

    <pre>foo
    bar</pre>

will be displayed as:

    foo bar

but should be displayed as:

    foo
    bar

The CSS equivalent for this is `white-space: pre`.

Sebastian

**Comment by BerndGabriel** [comment]
Cannot reproduce with commit 2da4c8289bd1b8d21d28932bb4845a10c6ab4290

**Comment by SebastianZ** [comment]
My fault, I tested in a program that replaced line breaks by spaces before displaying the contents. :disappointed:
Sorry for the noise!

Sebastian
