### ISSUE TITLE
THtmlView on Linux overload WidgetSet.AppProcessMessages and prevent closing modal forms.

### ISSUE THREAD

**Issue by MaxTerentiev** [BerndGabriel/HtmlViewer#142]
THtmlView 11.6-to-11.7 + Lazarus 1.4.4 on Linux overload messages queue, eat 100% CPU and prevent closing modal forms. I try to debug it and looks like THtmlView infinity send PAINT and/or RESIZE messages, so WidgetSet.AppProcessMessages in CustomForm.inc->ShowModal never returns and modal forms can't close. Workaround is changing size of THtmlView: if width/height of THtmlView changed - it's breaks we inifinity loop and modal forms can be closed.

Attached sample project to reproduce problem.

[HtmlViewBug.zip](https://github.com/BerndGabriel/HtmlViewer/files/325197/HtmlViewBug.zip)

**Comment by BerndGabriel** [comment]
The fix breaks the endless message loop by immediately updating the PaintPanel instead of just invalidating it after loading a document.
