### ISSUE TITLE
Clickable links at top of HtmlViewer after LoadFromString

### ISSUE THREAD

**Issue by LarsDB** [BerndGabriel/HtmlViewer#144]
Using THtmlViewer in a TFrame, and after LoadFromString everything looks fine except all non-visible links (the ones below bottom of visible range -> the ones that needs to be scrolled into view) are all stacked on top of eachother at the top of the document. 
There's no visible indication of them being there, but MouseMove reports the links to be present, and they are clickable (there's handpoint-cursor + HotSpotClicked gets fired)

**Comment by BerndGabriel** [comment]
Looks like this issue does not depend on TFrame and LoadFromString. 
It rather happens always until the link has been visible.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Commit e0a47bc7f5170ebc77456b75c477d40112953d7a fixes it.
