### ISSUE TITLE
HTMLViewer (branch 11.6-to-11.7) not installing on Lazarus 1.6

### ISSUE THREAD

**Issue by chriseana** [BerndGabriel/HtmlViewer#145]
Hi Bernd, 
Iḿ using branch 11.6-to-11.7. Iḿ receiving this error now :(

Compile package FrameViewer09 11.0: Exit code 256, Errors: 1, Warnings: 31, Hints: 10
htmlmisc.pas(309,36) Warning: Symbol "CM_WININICHANGE" is not implemented
htmlmisc.pas(621,13) Hint: Conversion between ordinals and pointers is not portable
htmlmisc.pas(630,13) Hint: Conversion between ordinals and pointers is not portable
htmlmisc.pas(648,11) Hint: Conversion between ordinals and pointers is not portable
htmlmisc.pas(731,15) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
htmlmisc.pas(753,10) Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"
htmlmisc.pas(860,10) Warning: Function result does not seem to be set
htmlmisc.pas(869,10) Warning: Function result does not seem to be set
htmlmisc.pas(976,26) Hint: Local variable "TM" does not seem to be initialized
htmlmisc.pas(1003,26) Hint: Local variable "TM" does not seem to be initialized
htmlmisc.pas(1027,10) Warning: Function result does not seem to be set
htmlmisc.pas(1036,10) Warning: Function result does not seem to be set
htmlmisc.pas(1045,10) Warning: Function result does not seem to be set
htmlmisc.pas(1054,10) Warning: Function result does not seem to be set
htmlmisc.pas(1110,10) Warning: Function result does not seem to be set
htmlmisc.pas(1119,10) Warning: Function result does not seem to be set
htmlmisc.pas(1129,10) Warning: Function result does not seem to be set
htmlmisc.pas(1138,10) Warning: Function result does not seem to be set
htmlmisc.pas(1147,10) Warning: Function result does not seem to be set
htmlmisc.pas(1156,10) Warning: Function result does not seem to be set
htmlmisc.pas(1165,10) Warning: Function result does not seem to be set
htmlmisc.pas(55,3) Hint: Unit "ctypes" not used in HtmlMisc
widestringslcl.pas(85,14) Warning: An inherited method is hidden by "Equals(TWideStrings):Boolean;"
widestringslcl.pas(415,28) Warning: Implicit string type conversion from "AnsiString" to "WideString"
widestringslcl.pas(542,34) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(563,39) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(812,31) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(812,27) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(862,43) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(898,22) Warning: Implicit string type conversion from "AnsiString" to "WideString"
widestringslcl.pas(922,43) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(1243,36) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(1243,32) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(1245,37) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
widestringslcl.pas(1245,33) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
HtmlGlobals.pas(524,36) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
HtmlGlobals.pas(554,36) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
HtmlGlobals.pas(867,3) Hint: Local const "ROP_DstCopy" is not used
HtmlGlobals.pas(1130,29) Hint: Local variable "Buffer" does not seem to be initialized
HtmlGlobals.pas(1216,13) Error: Identifier not found "RunCommand"
HtmlGlobals.pas(1326,39) Hint: Local variable "Pt" does not seem to be initialized
HtmlGlobals.pas(1383,39) Hint: Local variable "Pt" does not seem to be initialized

**Comment by BerndGabriel** [comment]
Sorry, Chris, I had already fixed it, but not yet committed. Now the commits are pushed and branch 11.6-to-11.7 should be usable with Linux/GTK2.
