### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by nicolasr75** [BerndGabriel/HtmlViewer#147]
Is there a possibility to use a custom font in local html documents that is not installed in the system?

Since I can't find _font-face_ in the code I guess CSS font-face is not supported.

Background is that I would like to use HtmlViewer for showing formatted text in a setup menu. Since it's a setup application I don't want to install the custom font in the system at that time. I could have it either in my exe resources or as a separate file.

**Comment by BerndGabriel** [comment]
You're guessing right, HtmlViewer does not support _font-face_. Currently it is not on the todo list.
