### ISSUE TITLE
Error display controls

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#148]
Standard controls on the page are not displayed at startup. They become visible only after a hold on them with the mouse.
![1](https://cloud.githubusercontent.com/assets/1192230/16532873/d432613a-3fe5-11e6-8ad3-87094f5159cf.png)
![1 zip](https://cloud.githubusercontent.com/assets/1192230/16533116/975ea604-3fe7-11e6-83fb-87b849d4808b.png)

**Comment by BerndGabriel** [comment]
Fixed.
