### ISSUE TITLE
Table borders

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#153]
Since the audit HtmlViewer-2a7a88a2c8a3a0d59ad98eeca651dddfce305aa1 table borders are wide and the text at all. Since the audit HtmlViewer-590a27e4bd3af158e244c301261abb4d5260cacf text in the table can be seen, but the borders remain wide.
![1](https://cloud.githubusercontent.com/assets/1192230/16644285/eab20a5a-442c-11e6-9b8c-f874b1b599fa.png)
![1 zip](https://cloud.githubusercontent.com/assets/1192230/16644294/f1e6a1b4-442c-11e6-9d1a-05801ec607d1.png)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 
Commit 52ca83d18f70fb0da11bddf8290631b4adba6da1 fixes it.
