### ISSUE TITLE
Entering to HtmlViewer control cause vertical scroll position reset

### ISSUE THREAD

**Issue by Dmitro25** [BerndGabriel/HtmlViewer#154]
An internal OnEnter event of HtmlViewer cause the vertical position of the scrolling is resetting to 0. 
To reproduce this put HTMLViewer and a Button on the form. On OnCreate form event load document in HTMLViewer. Change vertical scrolling position of document. Then set focus to the button and then use Tab key to change focus to HTMLViewer. The scrolling position is reset to 0. The same thing happens if you create a PageControl with two TabSheets, each of which has HTMLViewer and switch between pages with the mouse (HTMLViewer must be have the input focus on both tabs).

**Comment by BerndGabriel** [comment]
Fixed!
Please notice that the fix sets correct coordinates. 
If you don't want to tab through links define NoTabLink in htmlcons.inc.
