### ISSUE TITLE
Feature request - HandCursor (or LinkCursor)

### ISSUE THREAD

**Issue by JohnSylver** [BerndGabriel/HtmlViewer#156]
Please add a HandCursor (or LinkCursor) property (like LoadCursor property), in order to use instead of the ugly default hand cursor loaded from resources. Please make its default value crHandPoint.

Thank you in advance.

**Comment by JohnSylver** [comment]
Actually it's just possible to replace the cursor in the Html32.res file. So I attach a zip containing the hand cursor and also other better looking cursors.
[HTMLViewer.Cursors.zip](https://github.com/BerndGabriel/HtmlViewer/files/358604/HTMLViewer.Cursors.zip)

**Comment by raelb** [comment]
@JohnSylver: How should the Html32.res file be replaced with the cursor in your zip file? Is it possible to provide the result file so I can just copy/paste over existing Html32.res?
Thanks

**Comment by raelb** [comment]
Actually a simpler thing to do is just comment out the line of code in `HtmlImages.pas` that assigns the HandCursor: 

  //Screen.Cursors[HandCursor] := LoadCursor(HInstance, MakeIntResource(Hand_Cursor));

**Comment by BerndGabriel** [comment]
Thanks for request and solution.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/29f59a124175fa07acc6f809528901f76eb9f7ae introduces define UseHandCursor to control the use of the ugly default cursor. By default it is defined and the ugly default cursor is used.
