### ISSUE TITLE
Frame pictures

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#158]
On some pages, images are displayed in a frame, for example in IE though this frame is not displayed. Sometimes it looks very bad when the background image should blend in with the background of the page. If this is not a bug in the source code and do everything according to the standard, it can be setup which allows you to enter optional disable a frame image?
![1](https://cloud.githubusercontent.com/assets/1192230/17226239/7f0998b0-5519-11e6-9d71-91c8b60160a3.png)
![1 zip](https://cloud.githubusercontent.com/assets/1192230/17226242/832bc346-5519-11e6-9df6-8be67c786107.png)

**Comment by BerndGabriel** [comment]
Fixed!
