### ISSUE TITLE
XHTML file is opened without any content

### ISSUE THREAD

**Issue by jonjbar** [BerndGabriel/HtmlViewer#161]
Using the FrameDemo.exe, try opening the attached XHTML file: its title is displayed correctly but it displays an empty content.

Problematic file: [chapter-008.zip](https://github.com/BerndGabriel/HtmlViewer/files/479878/chapter-008.zip)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Commit 322c8a41b232e483c880c2a2f770c601d3c21df3 fixes it.
