### ISSUE TITLE
Error Image

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#163]
After the latest updates were mistakes:
1. Missing icons in the absence of images.
2. Even in the absence of the image frame where the image should be reduced.
3. In some cases, the image is strongly increased.

The test cases are necessary?
![1](https://cloud.githubusercontent.com/assets/1192230/18800170/98f57758-81ec-11e6-931a-fec4119b5dfd.png)
![2](https://cloud.githubusercontent.com/assets/1192230/18800172/9bdbfcd0-81ec-11e6-88b7-ac0eb996cd52.png)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 
> The test cases are necessary?
Would be easier to test. Maybe you can post a link if it is a publicly available page (not a session or user specific page) or skip the images except the first three images.

**Comment by SchwarzKopf-M** [comment]
Spread test pages as typical.
![err zip](https://cloud.githubusercontent.com/assets/1192230/18802559/960f92e0-81fa-11e6-933e-acc913db8dba.png)

**Comment by BerndGabriel** [comment]
Fixed in master branch.
