### ISSUE TITLE
document manipulating

### ISSUE THREAD

**Issue by landrix** [BerndGabriel/HtmlViewer#164]
Hello,

after loading a html-page, is it additional possible to manipulate the document?

for instance, if i have DIV with id xy, i want to add a new DIV to this element. the view needs simple repaintet. or second, remove the last added DIV.

Thanks

**Comment by BerndGabriel** [comment]
I never tried it but modifying a ThtDocument should be possible.

There are some restrictions I recall from the scratch: 

- You should modify block level elements only as inline level elements are combined into TSections while reading the document. 
- You cannot depend on CSS styles as they are processed while reading the document, too. Instead you must feed the constructor with effective Attributes:TAttributeList and Properties:TProperties. Please note that Attributes and Properties are owned by the caller although currently erroneously stored in THtmlNode by reference.
- Adding text will be a hard job as you have to add a TSection. You might want to use the various Add methods. Before using AddTokenObj, which adds a string to the section, you must push the Properties:TProperties to the documents PropStack.
- You should study ReadHtml.pas to find out which element is represented by which class.
- Do not modify property Display to a value that calculates to inline as "inline" is not supported unless the element tree is converted to a TSection.

After modifying a ThtDocument:

- call THtmlViewer.Reformat
- you cannot use methods like CopyToClipboard as the source code is not generated by the document but the original code is referenced only

If you still want to modify a ThtDocument we'd be interested in your proceedings!

**Comment by landrix** [comment]
Thank you - schould i close the issue? I think the information could also be something for the Wiki. So she will not be lost.
