### ISSUE TITLE
THtmlViewer.HTMLMouseMove bug with active scrollbar (PtInObject failing)

### ISSUE THREAD

**Issue by rfsoftware** [BerndGabriel/HtmlViewer#166]
First of all, this is a new bug in 11.6 and 11.7 (11.5 not tested). In 11.4 everything works well and there is no issue with it.

For some reason the PtInObject calls in THtmlViewer.HTMLMouseMove seems not anymore correctly to work, as soon the scrollbar is used. It doesn't anymore detect the mouse move correctly on any images.

If you move the scrollbar to the bottom and move it back a little bit up, PtInObject has issues in not anymore correctly find the objects under the mouse cursor.

I have attached a sample html file to test this.

Steps:
1. Place a THTMLViewer component on a form and add an OnCreate Event: HTMLViewer1.Load('VideoBrowserBug.html);
2 Now run the application and size the window so that the HTMLViewer gets a scrollbar. You should see the Point cursor as soon you move over the images. This is OK so far.
3. Scoll to the bottom of the file and back up about the half way. Now move the mouse again over the images. You should now see, that they don't anymore react on the mouse move and show the text cursror instead. Also any ImageClick events will not fire anymore as it doesn't correctly find the Object under the cursor now.

This worked without an issue in 11.4.

Attached Image and HTML file (rename txt to html):
[VideoBrowserBug.txt](https://github.com/BerndGabriel/HtmlViewer/files/553886/VideoBrowserBug.txt)
![image](https://cloud.githubusercontent.com/assets/9846237/19735394/adc37d78-9bab-11e6-9ab9-94b0994fb3e0.jpg)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

https://github.com/BerndGabriel/HtmlViewer/commit/4122b0e074aa12603083533ff322b576be928e22 fixes it in master branch.
