### ISSUE TITLE
Error image

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#168]
The latest versions of the image icon which appeared previously not displayed.
![11](https://cloud.githubusercontent.com/assets/1192230/20456228/7fa5ed84-ae8b-11e6-86a7-959ebc82087f.png)
![1 rar](https://cloud.githubusercontent.com/assets/1192230/20456230/8534af88-ae8b-11e6-9225-3a852251a75f.png)

**Comment by BerndGabriel** [comment]
1) The image looks like a screenshot or FrameDem.exe. FrameDem.exe can load images from local file systems only but not from internet.
2) Even FrameBrowserDemo*.exe and Forefox do not show an image different than the error image. Therefore I close this issue.

**Comment by SchwarzKopf-M** [comment]
Yes, this is a screenshot FrameDem.exe. But this image of 1x1 pixels, and it is not loaded if you use another application with access to the Internet on a component basis.

**Comment by BerndGabriel** [comment]
"1x1 pixels" is an important info. I'll check that again!
Thanks

**Comment by BerndGabriel** [comment]
The downloaded file is a text file with 3 LF and 1 CR characters. Obviously not an image and thus the error image is shown instead.
