### ISSUE TITLE
Error image

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#170]
Perhaps the image error. Visually it is seen that the picture below and to the right is cut off at a pixel.
![33](https://cloud.githubusercontent.com/assets/1192230/20456329/4630f1e0-ae8e-11e6-9782-5f91f2416c5a.png)
![3 rar](https://cloud.githubusercontent.com/assets/1192230/20456331/4f942928-ae8e-11e6-825f-ebf7596473b7.png)

**Comment by BerndGabriel** [comment]
Fixed in master branch
