### ISSUE TITLE
Add embedded images directly into HTML

### ISSUE THREAD

**Issue by jaclas** [BerndGabriel/HtmlViewer#174]
Please add this feature:

http://www.techerator.com/2011/12/how-to-embed-images-directly-into-your-html/

**Comment by BerndGabriel** [comment]
![base64beastie](https://cloud.githubusercontent.com/assets/90834/22404290/eac0c5ba-e62d-11e6-9ae0-b9a6164d3181.png)
Yeah, has been added some years ago!
