### ISSUE TITLE
Installing in XE8 on Windows 10 Pro

### ISSUE THREAD

**Issue by PeterXE8** [BerndGabriel/HtmlViewer#176]
Hello
I have opened the FrameViewerXE8.droj, selected Release configuration and Win64 platform and the bpl compiled successfully. When I attempt to install the package (Component | Install packages), an error message displays "Can't load package <Path to file>\FrameViewerXE8.bpl, %1 is not a valid Win32 application".
What should I do to install the components?
Regards, and thanks in advance

**Comment by BerndGabriel** [comment]
Hi
As BDS is a 32-bit application you must compile a 32-bit version of
FrameViewerXE8 to install. Nevertheless your applications can be
compiled as 64-bit-applications.

Am 27.01.2017 um 02:23 schrieb PeterXE8:

**Comment by PeterXE8** [comment]
I have set the Library path to D:\Peter\Documents\Embarcadero\Studio\HTMLViewer 11.7, which is the path that contains the '\source\' folder, and now get the following error:

[dcc32 Fatal Error] FrameViewerXE8.dpk(71): F2048 Bad unit format: '..\source\BegaHtmlPrintPreviewForm.dcu' - Expected version: 29.0, Windows Unicode(x86) Found version: 29.0, Windows Unicode(x64)

I do not understand the error.

Regards

**Comment by PeterXE8** [comment]
Sorry, it is perfectly obvious that the previously compiled 64 bit DCE files were still in the source folder. I removed them and it compiled Ok. I clicked on Component\Install packages\Add, selected the FrameViewerXE8.bpl, but I received an error message saying that FrameViewerXE8.bpl can't be installed because it is not a design time package.
How should I proceed?
Regards

**Comment by PeterXE8** [comment]
I found the design time package: dclFrameViewerXE8.dpk, compiled it, right clicked on Install, fixed some further Library path issues, and it is installed.
