### ISSUE TITLE
Bad recognize kind of image

### ISSUE THREAD

**Issue by jaclas** [BerndGabriel/HtmlViewer#179]
Function KindOfImage() from HtmlImages.pas not recognize this image kind:

https://pl.wikipedia.org/wiki/Pies_domowy#/media/File:Collage_of_Nine_Dogs.jpg

result is itNone

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
I cannot reproduce it with a downloaded copy of that file.
On which kind of hardware and operating system did you find the issue?

**Comment by jaclas** [comment]
Oh, my mistake...sorry! I not check that this link is not directly to file but page... sorry again, please close issue :-)
