### ISSUE TITLE
Rendering not as expected

### ISSUE THREAD

**Issue by hafedh-trimeche** [BerndGabriel/HtmlViewer#185]
This file (Acq.html) is not rendered as expected.
The cells of the the table are larger then those displayed under IE & Firefox.

[Acq.zip](https://github.com/BerndGabriel/HtmlViewer/files/1040476/Acq.zip)

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/9cdd2aef697bb0323074b413abb844594b9622ef removes most spaces. 

Spaces in rows 'Request' and 'Response' are still there as of the unexpected <head> after <p> which ends <p> in HtmlViewer and the following <code> is renderer as another block.
