### ISSUE TITLE
Cannot compile if NoMetaFile directive active

### ISSUE THREAD

**Issue by jakmoy** [BerndGabriel/HtmlViewer#188]
Define **NoMetaFile** directive in htmlIcons.inc.
Cannot compile htmlview.pas because of missing implementation of function THtmlViewer.MakePagedMetaFiles

**Comment by BerndGabriel** [comment]
Do you mean THtmlViewer.MatchMediaQuery(). That's what I was missing. If not, which HtmlViewer version, OS and compiler?

**Comment by BerndGabriel** [comment]
MIssing THtmlViewer.MatchMediaQuery() fixed in master branch
