### ISSUE TITLE
Missing decl of MatchMeduaQuery+ fix

### ISSUE THREAD

**Issue by Alexey-T** [BerndGabriel/HtmlViewer#189]
default options, on Ubuntu 16.
htmlview.pas(342,15) Error: Forward declaration not solved "MatchMediaQuery(TObject;const ThtMediaQuery;var Boolean);"

function is inside {$ifdef NoMetaFile} so it is not reachable on Linux.
To fix:
htmlview.pas

line 3425:
{$ifndef NoMetaFile}
line 3719
{$endif}

before $endif add:

```
{$else}
procedure THtmlViewer.MatchMediaQuery(Sender: TObject; const MediaQuery: ThtMediaQuery; var MediaMatchesQuery: Boolean);
begin
  //empty
end;
```

**Comment by BerndGabriel** [comment]
fixed in master branch some days ago and now in branch HtmlViewer 11.8 as well.
