### ISSUE TITLE
Crash of Lazarus demo HtmlDemo

### ISSUE THREAD

**Issue by Alexey-T** [BerndGabriel/HtmlViewer#190]
On opening from File menu this HTML file. attach in zip.
It is russian filename with 35K length line (such file is made by Yandex, big russian firm, i got file by downloading site www.ya.ru ).

Lazarus 1.9 trunk,
Ubuntu 16.4 x64 gtk2

[yandex-test.zip](https://github.com/BerndGabriel/HtmlViewer/files/1125308/yandex-test.zip)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Fixed in branches master and 11.8
