### ISSUE TITLE
Please return access to table properties

### ISSUE THREAD

**Issue by trichview** [BerndGabriel/HtmlViewer#199]
In v11.8, the following properties of THtmlTable became private:
BkGnd, BkColor, CellSpacingVert, CellSpacingHorz, CellPadding.

This is a problem for us, we need them for our HTML importer (reading document from THTMLViewer in our TRichViewEdit)
Please return access to these properties; may be a read-only access...

**Comment by BerndGabriel** [comment]
BkGnd, BkColor, CellSpacingVert, CellSpacingHorz, and CellPadding are public read-only properties now.
