### ISSUE TITLE
Bugs with Lazarus 1.8rc4

### ISSUE THREAD

**Issue by EganSolo** [BerndGabriel/HtmlViewer#201]
I downloaded the 11.8 package and when compiling under Lazarus the following errors pop-up:
1.Units uses LCLPlatformDef; is missing from unit HTMLMisc. Added it under implementation. It's required by this bit of code:
```pascal
initialization
  htExpectsUTF8 := WidgetSet.LCLPlatform in [lpCarbon, lpQt, lpGTK2, lpWin32];       
  //the constants lpCarbon etc are in LCLPlatformDef
```
2. In unit  *vwPrint* This is a bit more problematic and my fix is most likely wrong:
````pascal
{$ifdef LCL}
      PrnDev := TPrinterDevice(Printer.Printers.Objects[Printer.PrinterIndex]);
{$if lcl_fullversion >= 1020000}
     //Original code:
      DevMode := PrnDev.DevModeA; //won't compile.
     //Modified code -- most likely wrong:
      DevMode := PDeviceMode(PrnDev.DevModeW);
{$else}
      DevMode := PrnDev.DevModeW;
{$ifend}
```

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
A fix will be abailable soon.

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/f55d6d326232ad1330a7429abc70f8283a3a2ebd fixes this issue.
