### ISSUE TITLE
Displaying a picture

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#204]
Hi dear.
I sent you a description and examples of errors on my personal mail. If you can fix the problem, it has existed for a long time.
In the latest version of the library, there was a problem with loading images as elements. Between the elements there is a gap of 1 pixel. Test examples sent by mail.
![11](https://user-images.githubusercontent.com/1192230/31912810-372ba19a-b856-11e7-98be-a0a917db1e67.png)

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/a1774c9315fe3caf3206044f2b497ba8e71eb51f fixes this issue in master branch
