### ISSUE TITLE
Bitmaps are printed transparently

### ISSUE THREAD

**Issue by jbartlau** [BerndGabriel/HtmlViewer#205]
Hi,

We see an issue similar to #202 with bitmaps. They are displayed well; but in print preview, the lower left corner's color is set as transparency color. The cause is this snippet:

...
if Result = nil then
      if Bitmap <> nil then
      begin
        if not (ImageFormat in [itGif]) then
        begin
          Transparent := LLCorner;
          Mask := GetImageMask(Bitmap, False, 0);
        end;
        Bitmap := ConvertImage(Bitmap);
        Result := ThtBitmapImage.Create(Bitmap, Mask, Transparent);
      end;
...

A workaround would thus be to prevent the mask from being used. However, this code will probably exist for some reason.  Can somebody shed some light on this behavior?

**Comment by BerndGabriel** [comment]
In my transparency test document the bmp image looks the same in HtmlViewer and print preview (unlink png images as reported in #202, see below). 

Could you please post an affected bmp image? Thank you.

![grafik](https://user-images.githubusercontent.com/90834/33526325-b5f36324-d83f-11e7-90b4-379e304d1745.png)

![grafik](https://user-images.githubusercontent.com/90834/33526324-a6bad70c-d83f-11e7-9097-d33fe6e03d69.png)

**Comment by jbartlau** [comment]
Thanks for looking at this. I attach a simple HTML file using the bitmap in question. For me, the result looks like this:

![screen](https://user-images.githubusercontent.com/1235493/33544118-c65f69de-d8d9-11e7-8e59-f6418e8b8cce.png)

Can you reproduce the effect on your end as well?

**Comment by BerndGabriel** [comment]
Sorry, no:
![grafik](https://user-images.githubusercontent.com/90834/33570770-2b9f64e4-d92e-11e7-80e0-576967a8867e.png)
Using HtmlViewer 11.8, Delphi XE5, Windows 10

**Comment by jbartlau** [comment]
OK, we tested with 11.6. Bummer - apologies.
