### ISSUE TITLE
Bug in HTMLSubs

### ISSUE THREAD

**Issue by landrix** [BerndGabriel/HtmlViewer#209]
in 11.7 PanelList was a TList
in 11.8 PanelList is a TPanelObjList

it should created with (false)
Line 7149 PanelList := TPanelObjList.Create(false);
Line 7175 PanelList := TPanelObjList.Create(false);

because TSection.Images holds the main-reference from the PanelList-Objects

destructor TSection.Destroy;
begin
...
  Images.Free; //AV, if TPanelObjList.Create(true);
...
end;

**Comment by BerndGabriel** [comment]
Thanks for spotting this elaborated issue.
Now fixed in master and 11.8
