### ISSUE TITLE
Superscript or subscript on first paragraph char not correct

### ISSUE THREAD

**Issue by JohnSylver** [BerndGabriel/HtmlViewer#216]
![superscript](https://user-images.githubusercontent.com/1853968/34321089-8049cb5c-e80f-11e7-97a4-659c4de5fde6.png)

**Comment by JohnSylver** [comment]
Was correct in previous 9.x versions.

**Comment by JohnSylver** [comment]
Hi,
Is there any fix or workaround fo this issue?
Thank you very much in advance.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Commit 25ecac8ab7189db332ea14ec6d41d62f7c47106a fixes it in branch master.
