### ISSUE TITLE
Support for max-width and max-height

### ISSUE THREAD

**Issue by coyoteelabs** [BerndGabriel/HtmlViewer#219]
Are there any plans to add support for max-width / max-height anytime soon (defined in CSS 2.1) ?

I've noticed some mentions of them in the code, but images won't cap the width/height to the defined values (the max-width/max-height values are ignored)

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/386f00b78dd75767a80e537469c043fb59825767 adds support for min/max-width/height for images and panels to the master branch
