### ISSUE TITLE
Demos on computers with two monitors

### ISSUE THREAD

**Issue by the-Arioch** [BerndGabriel/HtmlViewer#220]
I have two monitors on my working place, left and right, for the IDE and for the program itself (or external docs, tools, etc).

When I run the Frame Compiled Demo it pops up right between the monitors, instead on either of them.

Reason is HtmlViewer\Demos\Main Demos\FDemUnit.dfm

object Form1: TForm1
....
  Position = poDesktopCenter
....

This should be changed to poScreenCenter :-)

**Comment by BerndGabriel** [comment]
Thanks for this hint.
