### ISSUE TITLE
Wrapping of negative numbers - do not break away minus from its digits

### ISSUE THREAD

**Issue by the-Arioch** [BerndGabriel/HtmlViewer#221]
If you include signed numbers in the text - the negative numbers may got wrapped weirdly.

I checked methods mentioned in the top google result - https://stackoverflow.com/questions/7691569/no-line-break-after-a-hyphen

The non-standard NOBR tag seems working. But all proper (compliant with de jure HTML/CSS standard) methods do not work.

Also, major browsers do not need any special handling for negative numbers, detecting this special case and preventing the break between minus and digits.

**Comment by the-Arioch** [comment]
Adding screenshots.
![negnum 1](https://user-images.githubusercontent.com/937774/35386554-5532eff6-01c4-11e8-82e1-a66383f79ebd.png)
![negnum 2](https://user-images.githubusercontent.com/937774/35386555-5557f68e-01c4-11e8-9902-76c5864bbfd3.png)

**Comment by the-Arioch** [comment]
Adding test case
[NegNum_sample.zip](https://github.com/BerndGabriel/HtmlViewer/files/1663787/NegNum_sample.zip)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/81504f2d89d475ea8b40385f1e9617f451e9c711 fixes it. 

Now wrapping after '-' is not allowed if a digit follows.

**Comment by the-Arioch** [comment]
Thanks. 

Guess it may also be worth to expand the goal from mere numbers to an arbitrary text using the SO-mentioned HTML/CSS ways to inhibit lines wrapping.

One of the things that concerned me was that even lacking special case numeric treatment, there were generic instructions to avoid words breaking, and they did not work...

It might also be important, because as I see in your commit you only made a special case for the ASCII minus character, but there can be more similar characters, including SGML entities like dash, emdash and some other SO-mentioned ones....
