### ISSUE TITLE
Installing in Lazarus

### ISSUE THREAD

**Issue by Irelam17** [BerndGabriel/HtmlViewer#222]
HTMLMISC.pas would not compile, in Htmlviewer 11.8,  line :
   htExpectsUTF8 := WidgetSet.LCLPlatform in [lpCarbon, lpQt, lpGTK2, lpWin32];
the four lp... definitions are not defined. I updated the line to htExpectsUTF8 := true; and Htmlmisc compiles ok.
 Should these names just be defined as Pointers?

**Comment by Irelam17** [comment]
I ran aDiff between 11.6 and 11.8 versions of Htmlmisc.pas and noted that these Consts were defined in 11.6. Can I add them to 11.8 code ?

**Comment by BerndGabriel** [comment]
The platforms are moved form Lazarus unit InterfaceBase.pp to LCLPlatformDef.pas in Lazarus 1.8.2

**Comment by BerndGabriel** [comment]
This has been fixed with commit f55d6d326232ad1330a7429abc70f8283a3a2ebd for issue #201 (Bugs with Lazarus 1.8rc4) in the master branch.

**Comment by skoro** [comment]
Could not compile on Lazarus 1.8.2 HtmlViewer the master branch:
`vwPrint.pas(114,47) Error: Identifier not found "PDeviceModeW"`

**Comment by Irelam17** [comment]
PdevicemodeW  is used when attempting to use Unicode content to be printed. If you are 
using Unicode you need to set the unicode flag at compile time.
Martin



On 2 Jun 2018 at 11:35, Alexei Skorobogatko wrote:

Date sent:	Sat, 02 Jun 2018 11:35:44 -0700
