### ISSUE TITLE
Error table in small window

### ISSUE THREAD

**Issue by SchwarzKopf-M** [BerndGabriel/HtmlViewer#229]
In the latest releases after October 2016, when you set a small window size, it distorts the table.
![0 rar](https://user-images.githubusercontent.com/1192230/38574892-873db610-3ce9-11e8-867b-7269dc42a360.png)
![1](https://user-images.githubusercontent.com/1192230/38574901-8b2f461c-3ce9-11e8-8cbd-0c92dccfe82c.png)

**Comment by BerndGabriel** [comment]
I cannot see any flaws due to small windows in the master branch. 
Please state issue more precise if it still exists there.

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/4f4bc98bdee93e63680b24a6790c80b13889951a fixes this issue.
