### ISSUE TITLE
FontSerif (and similars) definitions

### ISSUE THREAD

**Issue by Micrologus** [BerndGabriel/HtmlViewer#233]
The htmlmisc.pas unit uses FontSerif and a few other similar variables in the initialization section

These variables are defined in HtmlGlobals.pas -- BUT only within MSWindows and Linux defines. Now that I'm compiling in Lazarus, FontSerif is NOT defined, and I have to add it myself...

So the solution is, I think, to fix HtmlGlobals and ensure that FontSerif and the other ones are initialized no matter what defines are present.

Thanks

**Comment by BerndGabriel** [comment]
MSWindows or Linux are defined in Lazarus. Other operating systems are not supported.
Which font names would you suggest to set for any other operating system?

**Comment by Micrologus** [comment]
The conditional define "darwin" indicates MacOS. I recently started using Lazarus on MacOS and after some research I have selected the following font names for THtmlViewer:

    {$ifdef darwin}
    FontSerif   = ThtString('Times');
    FontMono    = ThtString('Courier');
    FontSans    = ThtString('Helvetica');
    FontCursive = ThtString('Apple Chancery');
    FontHelvet  = ThtString('Helvetica');
    {$endif darwin}

These choices were ultimately based on these suggestions:

https://webmasters.stackexchange.com/questions/33793/what-is-the-default-serif-sans-serif-and-monospace-font-family-for-mac-os-x

https://apple.stackexchange.com/questions/315117/what-is-the-default-cursive-font-for-macos
