### ISSUE TITLE
ThtBitmal constructor: reintroduce, not overload (HtmlGlobals.pas)

### ISSUE THREAD

**Issue by Micrologus** [BerndGabriel/HtmlViewer#234]
(Using Delphi 7)

In the file HtmlGlobals.pas I believe that this line:

    constructor Create(WithTransparentMask: Boolean = False); overload;

must be instead:

    constructor Create(WithTransparentMask: Boolean = False); reintroduce;

My understanding is that 'overload' is when there are multiple methods with the same name. In this case there is only one method. Now, override cannot be used, because the ancestor class has different parameters (no parameters to be precise). So what is needed is "reintroduce", to override the constructor with different parameters. The implementation by the was is OK, it calls "inherited Create" and then does its own thing with the new parameter. But reintroduce is necessary, at least in Delphi 7 which I am using.

Thanks :)

Marco

**Comment by Micrologus** [comment]
Actually there is more...

1) The ThtBitmap constructor should also be 'virtual'. I.e:

constructor Create(WithTransparentMask: Boolean = False); overload;

2)

In HTMLGif2, TGIFImage is inherited from ThtBitmap and so the constructor must be updated accordingly, for example:

    constructor Create(Transp: boolean = False); override;

**Comment by BerndGabriel** [comment]
Thanks for asking. 'overload' is intended here. It allows TGIFImage to overide the parameterless Create defined in TBitmap resp. TGraphic while in ThtBitmap there is no need to override it as there is nothing to initialize.
