### ISSUE TITLE
Replace WideString->UnicodeString

### ISSUE THREAD

**Issue by Alexey-T** [BerndGabriel/HtmlViewer#239]
for Lazarus.
UnicodeString is faster. It uses ref counter. So when strings are assigned this works faster by ref counter.

change in HtmlGlobals, WideStringsLcl etc.

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/eee8879d1c6e07fb5763acfd263fd179599c5169 changes to UnicodeString for FreePascal >= 3.0. 

Tested with Lazarus 1.2.2 (FreePascal < 3.0) and 2.0.2 (FreePascal >= 3.0) and some Unicode-Delphis.
