### ISSUE TITLE
11.8 has no release

### ISSUE THREAD

**Issue by Memnarch** [BerndGabriel/HtmlViewer#241]
Didn't norice the 11.8 version at first, as it has no release but a tag only

**Comment by Memnarch** [comment]
btw i noticed there are commits after the 11.8 tag which are part of the 11.8 branch. Isn't it more suitable here to create a 11.8.1 Tag/Release?

**Comment by BerndGabriel** [comment]
Hi, after releasing a version on sourceforge.net I create a new branch and tag it and commit bug fixes to that branch without further sub releasing.

**Comment by Memnarch** [comment]
Well I'd expect the 1.8 branch to be at least named slightly different (i.e. 11.8.1) to reflect that this is not the same as the 11.8 release. On github people would expect that otherwhise.
