### ISSUE TITLE
HR tag always paints itself all the way to the right

### ISSUE THREAD

**Issue by Micrologus** [BerndGabriel/HtmlViewer#243]
This is about the <hr> tag. Depending on "width" and "align", the horizontal line should calculate a starting and ending point on the X horizontal, and paint itself from point x1 to point x2. The bug is that no matter what is defined in width and align, point x2 is always all the way to the right of the control.

Try to put a few <hr> tags and see for yourself:

<hr width=100 align=center> (should be 100 pixels in the middle, it starts 50 pixels left of the middle and goes all the way to the right)

<hr width=50 align=left> (should be 50 pixels on the left, it goes all the way to the right and takes the whole screen)

etc.

Thanks for the great work with this control.

MB

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 
Commit https://github.com/BerndGabriel/HtmlViewer/commit/1c3e4f34cf3fc301bd1014704b40ae1d4ebefca8 fixes it in master branch.
