### ISSUE TITLE
StyleEndSy not handled in ReadHTML.pas and triggers Assert exception

### ISSUE THREAD

**Issue by Micrologus** [BerndGabriel/HtmlViewer#245]
In THtmlParser.DoCommonSy I had to add an entry for the StyleEndSy tag, which was missing.

After my addition, the bottom of THtmlParser.DoCommonSy looks like this, and doesn't trigger the exception any more:

    StyleEndSy:  // NOTE: I added this...
        Next;  // NOTE: ..not 100% sure this is enough, but it seems to work fine...

    StyleSy:
      begin
        DoStyle(LCh, Doc, '', '', False);
        Next;
      end;
    else
      begin  // NOTE: previously the assertion was failing because StyleEndSy was not handled:
        Assert(False, 'DoCommon can''t handle <' + SymbToStr(Sy) + GreaterChar);
        Next; {as loop protection}
      end;

...and that is that... thanks and all the best to everyone :)

Marco

**Comment by Micrologus** [comment]
I couldn't immediately find an example document that triggers the
exception, but try this source HTML:

before <style> </style> after

And you will see that "after" is not shown. I don't know if it's related to
the main problem.

I'll keep looking and will try to reproduce the exception and let you know.

Thanks

**Comment by Micrologus** [comment]
Here is a sample HTML document which triggers the assert exception:

    <html><head> <style>  </style> </head> </html>

Notice that if you remove the "x", there will be no exception, e.g.

    <html><head> <style>  </style> </head> </html>
    (no exception here)

However if you put anything at all inside the comments  then the exception is triggered.

Also notice that if Assert exceptions are disabled, everything seems to work, because after the Assert statement there is a Next statement, which consumes the </style> tag (StyleEndSy) and I suspect that is why this situation was not noticed before.

Thanks

**Comment by BerndGabriel** [comment]
I cannot reproduce the assertion in master branch with Delphi 10.2 (FrameDem.exe, HtmlDemo.exe, HtmlEditor.exe) and Lazarus 1.8.2 (FrameDem.exe). 

Which compiler are you using and which HtmlViewer method do you use to load the document?

**Comment by Micrologus** [comment]
I'm using Lazarus 1.8.4 (fpc 3.0.4) and I call LoadFromString to load the document.

I'm attaching a small Lazarus project which should help reproduce the problem. To be sure, I also included the THtmlViewer source from the master branch which I'm using. (I tried with 11.8 and master branch, both versions cause the same error)

Note that you will only see the problem is you enable assertions in Project Options > Compiler, which is enabled in the settings of this attached project.

So please open "project1" with Lazarus, build, and run. The 3 buttons will:

1. Open a document which works fine
2. Open a document with the assert exception
3. Open a document which shows another problem I discovered with the <style> tag, which you can see for yourself.

Thanks

Marco

[StyleBugDemo.zip](https://github.com/BerndGabriel/HtmlViewer/files/2233692/StyleBugDemo.zip)

**Comment by BerndGabriel** [comment]
Thanks for spotting these issues.

Commits https://github.com/BerndGabriel/HtmlViewer/commit/f534d4ecf61dddbe17788d358a1efb95e35fc62f and https://github.com/BerndGabriel/HtmlViewer/commit/f444be53cf2fa10acd0504b11fd0921f86e8b62e fix them.
