### ISSUE TITLE
THtmlViewer show html work fine, but after click, it't show nothing

### ISSUE THREAD

**Issue by ZenoGuo** [BerndGabriel/HtmlViewer#246]
THtmlViewer show html work fine, but after click HtmlViewer, it's show nothing
win8 64 + **lazarus64** LCL GUI + THtmlViewer
htmlviewer1.LoadFromString('this is a test');

but win8 64 + delphi32 +THtmlViewer work fine...

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

https://github.com/BerndGabriel/HtmlViewer/commit/ac1fd1f53779efb9a4357523b01ba2c7cae148b7 fixes it in branch master.

**Comment by ZenoGuo** [comment]
thanks :)
