### ISSUE TITLE
RadioButton Cannot Group

### ISSUE THREAD

**Issue by TaiWinPin** [BerndGabriel/HtmlViewer#248]
My operating system: Windows 7
Delphi XE5
HTML-Viewer Vers .: 11.8
My Html Content:
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
 <html>
 <head>
     <meta http-equiv="content-type" content="text/html; charset=utf8">
     <title>Radio Group Test</title>
 </head> 
 <body>
	<div name="Question1" >Question1?
            <input type="radio"  name="Q1"  value="Y">Yes
            <input type="radio"  name="Q1"  value="N">No
        </div>
	<br>
	<div name="Question2" >Question2?
            <input type="radio"  name="Q2"  value="Y">Yes
            <input type="radio"  name="Q2"  value="N">No
	</div>
 </body>
 </html>

**Comment by TaiWinPin** [comment]
Sorry ### !!
My Html Content:
<textarea cols=80 rows=20 > 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf8">
<title>Radio Group Test</title>
</head> 
<body>
<div name="Question1" >Question1?
<input type="radio"  name="Q1"  value="Y">Yes
<input type="radio"  name="Q1"  value="N">No
</div>
<br>
<div name="Question2" >Question2?
<input type="radio"  name="Q2"  value="Y">Yes
<input type="radio"  name="Q2"  value="N">No
</div>
</body>
</html>
</textarea>

**Comment by TaiWinPin** [comment]
Sorry, I am not familiar with how to paste HTML Code.
I post it again.

&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv="content-type" content="text/html; charset=utf8"&gt;
&lt;title&gt;Radio Group Test&lt;/title&gt;
&lt;/head&gt; 
&lt;body&gt;
&lt;div name="Question1" &gt;Question1?
&lt;input type="radio"  name="Q1"  value="Y"&gt;Yes
&lt;input type="radio"  name="Q1"  value="N"&gt;No
&lt;/div&gt;
&lt;br&gt;
&lt;div name="Question2" &gt;Question2?
&lt;input type="radio"  name="Q2"  value="Y"&gt;Yes
&lt;input type="radio"  name="Q2"  value="N"&gt;No
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by TaiWinPin** [comment]
Finally,I use Version 11.7  Resolution This problem

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/83ae4f9305ed92de18ae9936fe070dcc642bd2cf fixes it in master branch.
