### ISSUE TITLE
Htmlmisc Devmode problem

### ISSUE THREAD

**Issue by irelam** [BerndGabriel/HtmlViewer#249]
Gabriel,
    Trying to compile the latest Htmlviewer 11.8.  Problem occurs when Lazarus tries to compile Htmlmisc.pas

Problem is on this statement:  DevMode := PrnDev.DevmodeA  ( stmnt 435)
devmodeA is not defined any where. Msg: ie Identifier idents no member "devmodeA"

Can I comment out the  {$if lcl_fullversion >= 1020000}  and just use 
DevMode := PrnDev.Devmode ?    

Martin
@BerndGabriel

**Comment by BerndGabriel** [comment]
Which Lazarus version are you using? A Version > 1.2.0.0? Maybe 1.2.0.0 is not the first version that needs devmodeA.
