### ISSUE TITLE
Unnecessary "Overload;" in function SubArray (HTMLSubs.pas)

### ISSUE THREAD

**Issue by Micrologus** [BerndGabriel/HtmlViewer#251]
function SubArray in unit HTMLSubs (implementation section) is marked as overload; even though there is no other function with the same name.

This is often harmless, but I just spent 6 hours to debug a Delphi compiler internal error message L681 that was ultimately due to some unnecessary "overload" statement. (Not in this particular unit and not in this library, but it was a similar situation, and it was while debugging that problem that I noticed the same thing here.)

Anyway I think that it would be better to remove that unnecessary "overload".

Thanks!

**Comment by BerndGabriel** [comment]
Thanks for spotting this unnecessary "Overload".

Commit https://github.com/BerndGabriel/HtmlViewer/commit/d58738d90237252fcd04df5487539460da2dcd33 "fixes" this issue.
