### ISSUE TITLE
Json Display problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [BerndGabriel/HtmlViewer#253]
Hi,
Please note that this code is not well rendered. IE, Firefox and Chrome did !

`<span>&#123;&#13;&#10;&#9;Host&#58;&#32;&quot;https&#58;//payer&#46;strongdata&#46;cloud/payment&quot;&#44;&#13;&#10;&#9;ResponseURL&#58;&#32;&quot;https&#58;//seller&#46;strongdata&#46;cloud/payment&quot;&#44;&#13;&#10;&#9;Mode&#58;&#32;&quot;txmYes&quot;&#44;&#13;&#10;&#9;Language&#58;&#32;&quot;en&quot;&#44;&#13;&#10;&#9;Account&#58;&#32;&quot;BA83283277F8999&quot;&#44;&#13;&#10;&#9;ProfileID&#58;&#32;1&#44;&#13;&#10;&#9;SessionTrack&#58;&#32;966906359&#44;&#13;&#10;&#9;Invoice&#58;&#32;&quot;96392358&quot;&#44;&#13;&#10;&#9;Description&#58;&#32;&quot;PGF&#32;PHP&#32;Test&quot;&#44;&#13;&#10;&#9;CurrencyCode&#58;&#32;840&#44;&#13;&#10;&#9;Amount&#58;&#32;200&#44;&#13;&#10;&#9;MAC&#58;&#32;&quot;cd68c4e8842c1f0aa5499fef093f3bde2051ed8c&quot;&#13;&#10;&#125;</span>`

The text version:
 { Host: "https://payer.strongdata.cloud/payment", ResponseURL: "https://seller.strongdata.cloud/payment", Mode: "txmYes", Language: "en", Account: "BA83283277F8999", ProfileID: 1, SessionTrack: 966906359, Invoice: "96392358", Description: "PGF PHP Test", CurrencyCode: 840, Amount: 200, MAC: "cd68c4e8842c1f0aa5499fef093f3bde2051ed8c" } 

Best regards.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/784666c58af6a87a0172bb58c84090dc7d38ce5a fixes it in master branch.
