### ISSUE TITLE
UTF* FindEX Compatibility

### ISSUE THREAD

**Issue by debritto** [BerndGabriel/HtmlViewer#259]
Hi folks,
The HTML Viewer component is at the heart of my application. 
Is it possible to make a text search using UTF8 characters? 
For example:
FindEx('investigação', false,false)

Best regards,
Christian

**Comment by dalxlab** [comment]
As I know - HtmlViewer use UnicodeString (WideString) inside. So - convert your UTF8 string to it.

**Comment by chriseana** [comment]
Hi @dalxlab ,
Thank you so much!
Warm regards from Brazil

**Comment by BerndGabriel** [comment]
@chriseana: was dalxlab's answer actually helpfully?

If not: which compiler do you use and why can't you use UnicodeString?
