### ISSUE TITLE
Question: (another) document manipulation

### ISSUE THREAD

**Issue by kqha** [BerndGabriel/HtmlViewer#261]
I think it's related to https://github.com/BerndGabriel/HtmlViewer/issues/164 but it seems my question is simpler. Consider I have this html

```
<html>
  <body>
    <span id="text1">This is text 1</span>
    <a href="#" id="link1">This is link 1</a>
  </body>
</html>
```

I need to modify some styling, says the font color or background color. How do I achieve that if I know the element ID only? I guess it's somehow related to IDDisplay, but cannot find any clue whatsoever in help files and demos.

**Comment by dalxlab** [comment]
I do some think like this (for Show or Hide some block):

```
for i := 0 to HtmlViewer.SectionList.IDNameList.Count-1 do
  if HtmlViewer.SectionList.IDNameList.Strings[i] = ... then
    begin
    if HtmlViewer.SectionList.IDNameList.Objects[i] is TBlock then
      TBlock(HtmlViewer.SectionList.IDNameList.Objects[i]).DisplayNone := True/False;
    end;
HtmlViewer.Reformat;
```

**Comment by kqha** [comment]
It appear to doesn't work for an "a" tag, this snippet from OnHotspotClick shows that it's a TChPosObj object type insead of a TBlock

```
if pvRender.SectionList.IDNameList.Objects[a].ClassNameIs(TBlock.ClassName) then
begin
  TBlock(pvRender.SectionList.IDNameList.Objects[a]).FGColor := clRed;
end
  else MessageBox(0,'Its not a TObject',PChar(pvRender.SectionList.IDNameList.Objects[a].ClassName),0);

```

**Comment by BerndGabriel** [comment]
HtmlViewer collects subsequent inline elements into a single TSection object and therefore it is not possible to find a single inline element in it. 

Fonts and colors of the resulting text in TSection are kept in TFontObj objects.

[HtmlGetFontObj.pas.txt](https://github.com/BerndGabriel/HtmlViewer/files/3639432/HtmlGetFontObj.pas.txt) offers a function that gets the first TFontObj of an inline element such as <a> or <b>.

Notice: This function works only if the TSection is not the last TSectionBase in the document. 
Notice: If there are embedded tags like in <a id='thisone'>x<b>y</b>z</a> the found TFontObj of Id = 'thisone' covers  'x' only as HtmlViewer creates a new one for the bolt 'y' and another one and for 'z'.
