### ISSUE TITLE
Get Content Height

### ISSUE THREAD

**Issue by mezen** [BerndGabriel/HtmlViewer#263]
Hi,

is it possibile to get the height of a loaded content?
I want to show multiple controls, each should has the height of the content (or a predefined max height).

Kind Regards,
mezen

**Comment by BerndGabriel** [comment]
Yes it is:
The content height in pixels is given in read only property THtmlViewer.MaxVertical.
The content width in pixels is given in read only property THtmlViewer.ScrollWidth.
