### ISSUE TITLE
Ability to include Components

### ISSUE THREAD

**Issue by trinione** [BerndGabriel/HtmlViewer#264]
Hello, 
How to place components on the Viewer?

For example, a 

`<table><tr><td>**<componet here>**</td></tr></table >`

This would provide significant design and layout advantages.

Regards.

**Comment by BerndGabriel** [comment]
You can use <panel> or <object> to insert VCL/LCL controls into the HTML document. 

Please refer to the HtmlViewer help for details.

Examples how to use these tags can be found in the demos "Flash" and "Panel".
