### ISSUE TITLE
Problem with Media attribute in a stylesheet link.

### ISSUE THREAD

**Issue by robBabiak** [BerndGabriel/HtmlViewer#265]
In THtmlViewer.MatchMediaQuery there is a problem if you have a CSS link with media="screen" which is valid according to the docs I have read. The body of this procedure assumes false, and them when it matches the type if there are no expressions (also valid is media="screen and (min- width: 480px) ) the length of MediaQuery.Expressions is 0 so it never sets OK to true and as a result the css link is not loaded. 

I think a simple check to see if the expression is empty after matching the MediaType would solve this issue. 

Changed Code for HtmlView.pas::THtmlViewer.MatchMediaQuery
var
  I: Integer;
  OK: Boolean;
begin
  OK := False;
  if (MediaQuery.MediaType in [mtAll, mtScreen]) xor MediaQuery.Negated then
  begin
   if length(MediaQuery.Expressions) = 0 then 
   begin
     OK := True;
   end else begin
      for I := Low(MediaQuery.Expressions) to High(MediaQuery.Expressions) do
      begin
        OK := EvaluateExpression(MediaQuery.Expressions[I]);
        if not OK then
          break;
       end;
    end;
  end;
  if OK then
    MediaMatchesQuery := True;
end;

Thanks.

**Comment by DanielPaepke** [comment]
We run into the same problem: We had an stylesheet with "allMedia" - but without any expressions and then our pages did not rendered with its existing and valid stylesheets. I agress with @robBabiak to fix this issue or simple set OK := True; before entering the loop:
...
OK := False;
if (MediaQuery.MediaType in [mtAll, mtScreen]) xor MediaQuery.Negated then
begin
OK := True; // init OK-value valid
for I := Low(MediaQuery.Expressions) to High(MediaQuery.Expressions) do
begin
  OK := EvaluateExpression(MediaQuery.Expressions[I]);
  if not OK then
	break;
end;
end;
if OK then
MediaMatchesQuery := True;
...
