### ISSUE TITLE
Image-Rendering unexpected between 11.6 and 11.9

### ISSUE THREAD

**Issue by DanielPaepke** [BerndGabriel/HtmlViewer#268]
Hello,

we are really happy with this HTML rendering component. Now I'm evaluating the latest version 11.9 as update-path to the currently used version 11.6. In a fast comparision of the compiled frame demo and its included samples I noticed that images not propably rendered between this two versions. Concretely it is about the example sample1.htm and the headline "HTML Graphics" and "Special Events". In version 11.6 the images are rendered as expected (comlete) - so I think. But in version 11.9 their content looks like "zommed". Can someone confirm that?

Thanks in advanced,
Daniel

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. 

Commit https://github.com/BerndGabriel/HtmlViewer/commit/935c6401e66af2226198a534ce00821af0c8ad6b fixes it in branch master.
