### ISSUE TITLE
HtmlViewer Delphi 10.1

### ISSUE THREAD

**Issue by ThelmaCottage** [BerndGabriel/HtmlViewer#270]
Where so I find HtmlViewer for Delphi 10.1 ? (I can see 10.2 and 10.3)

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/e7e96247fb1b63f59ddfcd2888793b354275b319 adds the missing files for Delphi 10 and 10.1
