### ISSUE TITLE
I cannot get this to install on Rad Studio 10.3

### ISSUE THREAD

**Issue by PrettyPegasus** [BerndGabriel/HtmlViewer#271]
So many issues dont know where to begin.  Directs say install into IDE, cant add as a design time package, cant add as a run-time package. compile issues etc.

**Comment by BerndGabriel** [comment]
Compile the projects in "HtmlViewer\Rad Studio 10.3\HtmlViewer.groupproj" and install dclFrameViewer260.bpl.
