### ISSUE TITLE
Line-Height stops Vertical-Align from working

### ISSUE THREAD

**Issue by MartinSedgewick** [BerndGabriel/HtmlViewer#272]
In the HTML below, the top table works, the bottom one doesnt.

When vertical-align is used alongside line-height, the line-height works, but vertical-align doesnt work.

```
<html>
<body>
  <table border="1" width="100%">
  <tr><td height="50" style="vertical-align:middle">hello</td></tr>
  <tr><td height="50" style="vertical-align:top" >hello</td></tr>
  </table>
  
  <table border="1" width="100%">
  <tr><td style="line-height:50px;vertical-align:middle">hello</td></tr>
  <tr><td style="line-height:50px;vertical-align:top" >hello</td></tr>
  </table>
</body>
</html>
```

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Commit https://github.com/BerndGabriel/HtmlViewer/commit/e25ac5688ee6c0b8b4032244a41260060b713e06 fixes this issue.
HtmlViewer respects "vertical-align" now. 

Firefox and Chrome seem to use "vertical-align:middle" in any case in the second table. If someone can tell me why, I might be able to let HtmlViewer do the same.
