### ISSUE TITLE
Incorrect parsing of href tags

### ISSUE THREAD

**Issue by csterg** [BerndGabriel/HtmlViewer#274]
Hello,
I run a very simple test like this:
`h.LoadFromString('<a href="index.php?item=1&pid=49">ITEM</a>');`
yet, the parsing of the & character is wrong: the href is parsed as if the &pid is an html entity.
Any insight pls?
Thanks

**Comment by csterg** [comment]
Found the problem:
`<html><body>&pid</body></html>`
loads as `πd`.
The `&pi` is parsed as the html entity `&pi;` but it does so even if the `;` is missing.
Any idea where to fix this?

**Comment by csterg** [comment]
Is this project dead?

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.
Commit https://github.com/BerndGabriel/HtmlViewer/commit/65dd267bacf356522fd234c813434b48fd968696 fixes it.
