### ISSUE TITLE
Width of 100% in table column works wrong and content is passed into the neighbouring cell

### ISSUE THREAD

**Issue by DanielPaepke** [BerndGabriel/HtmlViewer#286]
It seems that there are problems with texts in a table column if they have defined a width of 100%. Unfortunately, longer text is not wrapped, but moves directly into the neighboring cell and overwrites the text there. Also a surrounding frame of a table cell shows the same behavior and then it moves into the next cell.

Here is a screenshot that shows the behavior using a simplified example in the FrameDemo and compares it in a browser:
[screen.png.txt](https://github.com/BerndGabriel/HtmlViewer/files/4918223/screen.png.txt)

The HTML used to simulate and analyze the behavior can be found here:
[HTML.html.txt](https://github.com/BerndGabriel/HtmlViewer/files/4918215/HTML.html.txt)

Does anybody knows how I could fix this issue? It would be nice to find a solution for that. If more information are needed, please let me know and I will try to support you.

Thanks in advanced,
Daniel

**Comment by DanielPaepke** [comment]
@BerndGabriel Is it possible to have a short look at this behavior to classify this issue in detail?

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue!

commit https://github.com/BerndGabriel/HtmlViewer/commit/10fc44f7a436c13ff05ecabbc0eebc46fc8a7c95 fixes it.

**Comment by DanielPaepke** [comment]
It seems to work fine - thanks a lot for fixing this issue!
