### ISSUE TITLE
some fonts are not justified

### ISSUE THREAD

**Issue by kitty801** [BerndGabriel/HtmlViewer#299]
I have simple html code
```

<FONT SIZE = 5>
<p style="font-family:calibri" align="justify">long long long simple text...</p>
</FONT>
```

In ThtmlViewer  some fonts are justified (ex. Arial), but other are not (ex. Calibri)
Why?
Is it a font issue or HTMLViewer?

**Comment by BerndGabriel** [comment]
[299.html.txt](https://github.com/BerndGabriel/HtmlViewer/files/10529646/299.html.txt)

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/21688fa4c1ad077505fc28c763bca256a1ecd977 fixes this issue in branch _master_.
