### ISSUE TITLE
TObjectList problem 

### ISSUE THREAD

**Issue by irelam2017** [BerndGabriel/HtmlViewer#305]
Delphi 10.4.2 Community has no definition for TObjectList, tried reverting to TList. errors. Got rid of all the references to THistory and got a compiler critical error termination.
Result is that I can't re-compile my existing Htmlviewer code. Suggestions please ?

**Comment by BerndGabriel** [comment]
Commit https://github.com/BerndGabriel/HtmlViewer/commit/f14f61853544318d86cdb56550b3def909e8a5d7 replaces all TObjectLists with generic TObjectList<>s in the master branch.

I tested in Tokyo. Could you please try it in Sydney or Alexandria? 

Thanks in advance for posting test results.
