### ISSUE TITLE
Center Tables not rendered

### ISSUE THREAD

**Issue by hafedh-trimeche** [BerndGabriel/HtmlViewer#306]
This CSS:
```
.center {
  margin-left: auto;
  margin-right: auto;
}
```
is not rendered when applied to a **table**.
https://www.w3schools.com/howto/howto_css_table_center.asp

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/04feffe8ec96e9d5078cf201a60af1afa38a62ba fixes it and #314
