### ISSUE TITLE
HTML not well rendered

### ISSUE THREAD

**Issue by hafedh-trimeche** [BerndGabriel/HtmlViewer#314]
Please note that the attached document is not well rendered.

Tested with Firefox and Edge and the rendering is OK.
[HTMLView.txt](https://github.com/BerndGabriel/HtmlViewer/files/8105544/HTMLView.txt)

Best regards.

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/04feffe8ec96e9d5078cf201a60af1afa38a62ba fixes it and #306
