### ISSUE TITLE
Master no longer builds on Delphi XE or earlier

### ISSUE THREAD

**Issue by magsys** [BerndGabriel/HtmlViewer#318]
The HtmlGlobals unit now uses Vcl.Graphics.TBitmap.DrawTransparent which was added with Delphi XE2, so the project will no longer build with earlier versions of Delphi.

I appreciate support for old versions has to stop at some point, but it should be made glaringly obvious when it is time to stop updating for older compilers. 

Angus

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/1e4c2cbb740bef36178a88cc6dfb4c446a9bbfcb fixes this issue.
