### ISSUE TITLE
Cannot build package missing Lcl...pas units

### ISSUE THREAD

**Issue by bryanwilkins1246** [BerndGabriel/HtmlViewer#320]
I am attempting to build the package on Delphi Seattle. I have been unable to get past HtmlMisc.pas as it cannot find a number of Lcl.....pas units, e.g. LclVersion.pas.
I have tried installing Lazarus which has these units but that was a dead end.
Can anyone help?

![image](https://user-images.githubusercontent.com/15316781/179879935-f2ea6def-a9f3-4fba-a263-2a56af8b3920.png)

**Comment by BerndGabriel** [comment]
You don't need HtmlMisc.pas for Delphi. It provides types, constants, and functions that fill in some gaps in the Lazarus LCL for compiling the ported THtmlViewer controls. 

What about the project files for Seattle in subdir "Rad Studio 10.1"?

**Comment by bryanwilkins1246** [comment]
Thanks. I commented out all the units that could not be found and then installed TMS Unicode component pack (https://www.tmssoftware.com/site/tmsuni.asp) and it all worked beautifully .
