### ISSUE TITLE
Is font embedding supported?

### ISSUE THREAD

**Issue by Dingo64** [BerndGabriel/HtmlViewer#322]
I tried to render this code but seems font embedding this way is not supported. Is there any other way to use fonts which are not installed on the system?

```
<style>
@font-face 
{
	font-family: Manrope;
	src: url(Manrope-Regular.ttf);
}
body
{
	font-family: Manrope;
}
</style>
```

I added some code to my Lazarus project and now I can use custom fonts but would be nice to do that from CSS.

```
  AddFontResource('Manrope.ttf');
  SendMessage(HWND_BROADCAST, WM_FONTCHANGE, 0, 0);    
```

**Comment by BerndGabriel** [comment]
HtmlViewer does not support fonts other than those installed on the system.
