### ISSUE TITLE
MHT-Files supported by HTMLViewer?

### ISSUE THREAD

**Issue by trichter2** [BerndGabriel/HtmlViewer#323]
Hello HTMLViewer-Team,
does the HTMLViewer component support MHT-Files?
In my application, I can import the file while using a stream; nevertheless, the imported Text is not usable. 
It has the wrong format and pictures will not be displayed.
Is there anything I can do to solve this problem?
With HTML-Files everything works perfectly.

Best Regards
Tom

**Comment by BerndGabriel** [comment]
Hi Tom, 
HtmlViewer does not support WebArchives.
You must unpack the archive before HtmlViewer can load it.

**Comment by trichter2** [comment]
Hi Bernd,
Okay, then I will give it a try. I appreciate your help.
