### ISSUE TITLE
'FullDisplaySize' adds Margins on Top and Bottom (2*14px)

### ISSUE THREAD

**Issue by lennartjohnen** [BerndGabriel/HtmlViewer#327]
Hello,

in our application we are using THTMLViewer to paint HTML-Content into the top-left corner of a table, but we do also use its function 'FullDisplaySize' to autofit the table cell around it.

However we have been running into the problem, that the return values height is exactly 28 pixels (2* 14 pixels) higher than it should be.

After digging through the code for a little we have been able to hypothesize that the value 'ParagraphSpace = 14', later stored i.e. in 'MargArray[MarginTop]'  is added to the height of a section early on and not properly removed again. This culminates in the return values of 'FullDisplaySize' always being 28 pixels higher than they actually need to be (14 on top, 14 on bottom).

Here you can see the (too high) measurements being applied within our application

![image](https://user-images.githubusercontent.com/90446642/201142609-c554bc7b-b14c-424d-abb4-bf4f15b91683.png)

and here is how it looks if we manually remove 28 pixels from the return values height:

![image](https://user-images.githubusercontent.com/90446642/201143214-790b7d32-9961-4025-a506-d35fbff8c29f.png)

This behaviour (with a constant difference of 24 pixels) also holds true for all other sizes of HTML-content we have tested with.

While permanently just removing 28 pixels seems to be a viable solution for us (at least right now), seeing this issue fixed would still be great and probably incentivize us to update to the newest version of HtmlViewer (we tested and made sure that the issue is still present in the Branch HtmlViewer-11.9)

**Comment by BerndGabriel** [comment]
Could you please test in master branch again and if the heigth issue still persists post or email a test file? I cannot produce unreasonalbe heights in my tests with a simple table or paragraph.
