### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by davidmcdonald** [BerndGabriel/HtmlViewer#332]
Was looking to add some simple html to a form in Lazarus, but I am not finding any documentation that will help expliain it to me. Is there a place to find the documentation?

**Comment by BerndGabriel** [comment]
Hi David,

just install the FrameViewer components (package frameviewr09.lpk) and drop a THtmlViewer onto your form.

You can use property Text to write an HTML string to it or one of the LoadFrom* methods to load HTML text from files or streams or resources. 

If your are not loading from a file but your HTML text references file resources, set property Base to the path, where to find files with relative file name references.

For more details please refer to HtmlHelp\THtmlViewer.chm or its sources starting with HtmlHelp\html\contents.htm. Most common tasks are introduced in HtmlHelp\html\using_the_thtmlviewer_component.htm.

See also the source code of the htmldemo program in "Demos\Main Demos\demounit.pas".

**Comment by davidmcdonald** [comment]
> Hi David,
> 
> just install the FrameViewer components (package frameviewr09.lpk) and drop a THtmlViewer onto your form.
> 
> You can use property Text to write an HTML string to it or one of the LoadFrom* methods to load HTML text from files or streams or resources.
> 
> If your are not loading from a file but your HTML text references file resources, set property Base to the path, where to find files with relative file name references.
> 
> For more details please refer to HtmlHelp\THtmlViewer.chm or its sources starting with HtmlHelp\html\contents.htm. Most common tasks are introduced in HtmlHelp\html\using_the_thtmlviewer_component.htm.
> 
> See also the source code of the htmldemo program in "Demos\Main Demos\demounit.pas".

Thank you very much. Looking through it now. I appreciate your fast response.  :)
