### ISSUE TITLE
How to install the components 

### ISSUE THREAD

**Issue by Toolfolks** [BerndGabriel/HtmlViewer#335]
Newbie to this stuff
Any docs on installation please.

**Comment by Toolfolks** [comment]
I found the following. There is no FrameViewer2011.


<html>
 
<style> body {font-size: 12pt; font-family: "Serif"; }</style><head>
<title></title>
<link REL="stylesheet" TYPE="text/css" HREF="demo.css"> 

</head>

<body CLASS="indent">
<p CLASS="heading"><a NAME="What">What are the HTML Viewer Components?</a></p>
<p>The HTML component set consists of the <b>THtmlViewer</b>, <b>TFrameViewer</b>, and <b>TFrameBrowser</b>
components. All three are HTML document display components:</p>


  | THtmlViewer | The basic component. THtmlViewer displays single (non-frame) documents. It also forms 	    the basis for the other two components.
-- | -- | --
  | Displays both Frame and single HTML documents. TFrameViewer is oriented more for local 	    file system use.
Also displays Frame and single HTML documents. However, TFrameBrower is oriented 	 toward Internet style protocols and URL usage. Additional code and/or components are generally required to get    data from other sources than the local file system.


<p>These components support most of the HTML 3.2 and HTML 4 specifications with some popular HTML 5 enhancements. 
Many Cascading Style Sheet properties are also supported. </p>
<ul>
<li>Cascading Stylesheets
</li>
<li>Frames
</li>
<li>Bitmap, GIF, JPEG, and PNG Images
<ul>
<li><img ALIGN="middle" ALT="Animated GIFs" HEIGHT="32" SRC="agif2.gif" WIDTH="181"></li>
<li>Transparent images
</li>
<li>Image caching
</li>
<li>Left and right floating images
</li>
<li>Image sizing attributes
</li>
<li>Client side image maps</li>
</ul></li>
<li>Large HTML files
</li>
<li>HTML Tables
</li>
<li>HTML Forms
</li>
<li>Font sizes, styles, and colors with HTML tags or default settings
</li>
<li>Background colors and images
</li>
<li>Formatted printing of the HTML document
</li>
<li>Print preview
</li>
<li>Text search
</li>
<li>Copy to clipboard
</li>
<li>Subscripts and superscripts</li>
</ul>
<p>While HTML documents are normally associated with the Internet, they are also very useful for displaying all
kinds of textual material such as documentation, helpfiles, etc. Graphics are easily incorporated in these
documents. </p>

<p CLASS="heading"><a NAME="Files">Files Supplied</a></p>
<pre>In "Demos\Compiled Framedemo"

   Demo.htm        This file
   *.htm           Frame files for Demo.htm
   FrameDem.exe    The TFrameViewer demo program
   Various image and sound files for demo

In "HtmlHelp"

   THtmlViewer.chm  Help file 
   html\*.*         Source files of help file
   images\*.*       Source files of help file
   Various html help project files

In "Source" 

   sourcecode for the THtmlViewer, TFrameViewer, and TFrameBrowser components

     HtmlView.pas, .dcr           		THtmlViewer
     FramView.pas, .dcr           		TFrameViewer
     FramBrwz.pas, .dcr           		TFrameBrowser
     BuffConv.pas
     BuffConvArrays.pas
     DitherUnit.pas
     GDIPL2A.pas
     HSLUtils.pas
     HtmlBuffer.pas
     HtmlCaches.pas
     HtmlFonts.pas
     htmlgif1.pas
     HTMLGif2.pas
     HtmlGlobals.pas
     HtmlImages.pas
     HtmlPrinter.pas
     Htmlsbs1.pas
     HTMLSubs.pas
     HtmlSymb.pas
     htmlun2.pas
     MetaFilePrinter.pas
     ReadHTML.pas
     StylePars.pas
     StyleTypes.pas
     StyleUn.pas
     URLConn.pas
     URLSubs.pas
     vwPrint.pas
     HtmlMisc.pas                        Lazarus only
     HtmlComp.lrs                        Lazarus only
     HtmlUn2.lrs                         Lazarus only
     WideStringsLcl.pas                  Lazarus only
     HTMLCompEdit.pas                    Designtime only
     FrameViewerReg.pas                  Designtime only

     FrameViewer09.lpk, .pas             Lazarus Package source file.            Recommended Lazarus Version for best HtmlViewer support >= 1.2 (Win), >= 1.4 (Linux)
     FrameViewer6.dpk, .res              Delphi 6 Package source file.           Uses TntControls for better unicode support.
     FrameViewer7.dpk, .res              Delphi 7 Package source file.           Uses TntControls for better unicode support.
     FrameViewer2005.dpk, .res           Delphi 2005 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2006.dpk, .res           Delphi 2006 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2007.dpk, .res           Delphi 2007 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2009.dpk, .res           Delphi 2009 Package source file.
     FrameViewer2010.dpk, .res           Delphi 2010 Package source file.
     FrameViewerXE.dpk, .res             Delphi XE  Runtime Package source file.
     FrameViewerXE2.dpk, .res            Delphi XE2 Runtime Package source file.
     FrameViewerXE3.dpk, .res            Delphi XE3 Runtime package source file.
     FrameViewerXE4.dpk, .res            Delphi XE4 Runtime package source file.
     FrameViewerXE5.dpk, .res            Delphi XE5 Runtime package source file.
     FrameViewerXE6.dpk, .res            Delphi XE6 Runtime package source file.
     FrameViewerXE7.dpk, .res            Delphi XE7 Runtime package source file.
     FrameViewerXE8.dpk, .res            Delphi XE8 Runtime package source file.
     FrameViewerXE9.dpk, .res            Delphi XE9 Runtime package source file.
     RAD Studio 10.2\FrameViewer.dpk     Delphi 10.2 Tokyo      Runtime package source file.  
     RAD Studio 10.3\FrameViewer.dpk     Delphi 10.3 Rio        Runtime package source file.  
     RAD Studio 10.4\FrameViewer.dpk     Delphi 10.4 Sydney     Runtime package source file.  
     RAD Studio 11\FrameViewer.dpk       Delphi 11   Alexandria Runtime package source file.    
     DclFrameViewerXE.dpk, .res          Delphi XE  Designtime package source file.
     DclFrameViewerXE2.dpk, .res         Delphi XE2 Designtime package source file.
     DclFrameViewerXE3.dpk, .res         Delphi XE3 Designtime package source file.
     DclFrameViewerXE4.dpk, .res         Delphi XE4 Designtime package source file.
     DclFrameViewerXE5.dpk, .res         Delphi XE5 Designtime package source file.
     DclFrameViewerXE6.dpk, .res         Delphi XE6 Designtime package source file.
     DclFrameViewerXE7.dpk, .res         Delphi XE7 Designtime package source file.
     DclFrameViewerXE8.dpk, .res         Delphi XE8 Designtime package source file.
     DclFrameViewerXE9.dpk, .res         Delphi XE9 Designtime package source file.
     RAD Studio 10.2\dclFrameViewer.dpk  Delphi 10.2 Tokyo      Designtime package source file.  
     RAD Studio 10.3\dclFrameViewer.dpk  Delphi 10.3 Rio        Designtime package source file.  
     RAD Studio 10.4\dclFrameViewer.dpk  Delphi 10.4 Sydney     Designtime package source file.  
     RAD Studio 11\dclFrameViewer.dpk    Delphi 11   Alexandria Designtime package source file.    
     HtmlView.chm                        The help file (Sorry, but most of it is still version 9.45)
   
   Source code for the print preview dialog TBegaHtmlPrintPreviewForm

     BegaHtmlPrintPreviewForm.pas
     BegaMetaFilePrinter.pas
     BegaPreview.pas, .dfm, .lfm
     BegaPreviewForm.pas, .dfm, .lfm
     BegaPreviewPanel.pas
     BegaScrollBox.pas
     BegaZoom.pas
     ZoomAndHandCursor.RES

In "Demos\Main Demos"
     
   Source code for the demo programs

     HtmlDemo.dpr, .res                      HtmlViewer demo using TNT Unicode Controls (UTF-16)
     HtmlDemoW.dpr, .res                     HtmlViewer demo using VCL Unicode Controls (UTF-16)
     HtmlDemoLaz.lpr, .res                   HtmlViewer demo using LCL Unicode Controls (UTF-8)
     FrameDem.dpr, .res                     FrameViewer demo using TNT Unicode Controls (UTF-16)
     FrameDemW.dpr, .res                    FrameViewer demo using VCL Unicode Controls (UTF-16)
     FrameDemLaz.lpr, .res                  FrameViewer demo using LCL Unicode Controls (UTF-8)
     FrameBrowserDemoIcs.dpr, .res         FrameBrowser demo using VCL Unicode Controls and ICS 7/8 Components
     FrameBrowserDemoId10.dpr, .res        FrameBrowser demo using VCL Unicode Controls and Indy 10 Components
     AuthorizeFormUnit.pas, .dfm, .lfm
     CacheUnit.pas
     demounit.pas, .dfm, .lfm
     DownloadFormUnit.pas, .dfm, .lfm
     fbHelpIcs7.res
     fbHelpIndy10.res
     FBrDemUnit.pas, .dfm, .lfm
     FDemUnit.pas, .dfm, .lfm
     FontDlg.pas, .dfm, .lfm
     GoPage.pas, .dfm, .lfm
     Grid.res
     Htmlabt.pas, .dfm, .lfm
     ImgForm.pas, .dfm, .lfm
     InfoFormUnit.pas, .dfm, .lfm
     LogFormUnit.pas, .dfm, .lfm
     manifest.res
     OptionsId10.inc
     PrintStatusForm.pas, .dfm, .lfm
     ProxyFormUnit.pas, .dfm, .lfm
     Submit.pas, .dfm, .lfm
     SubmitTNT.pas, .dfm
     UrlConIcs.pas
     UrlConId10.pas
     UrlConVclZip.pas

In "Demos\Other Demos"     

   Some more demo projects and source files. For example the FrameBrowser demos 
     
     FrameBrowserUsingICSv7 
     FrameBrowserUsingIndy10
</pre>

<div style="age-break-inside: avoid">
<p CLASS="heading"><a NAME="InstallViewer">Installing The HTML Components</a></p>
<p>If you are installing for more than one version of Delphi, use separate directories for the installations. </p>
<p>Installation problems are almost always due to old or incorrect files being accessed. Make sure that the
Library Path or Search Path does not point to the directory of any old HTML component files. The Library Path can
be edited from the <b>Tools|Environment</b> Options dialog, <b>Library</b> tab. The Search Path from the
<b>Project|Options</b> dialog, <b>Directories/Conditionals</b> tab.</p>
</div>
<p>Delete all DCU files generated with previous installations. </p>
<p>The Register procedures in <code>HTMLVIEW.PAS</code>, <code>FRAMVIEW.PAS</code>, and <code>FRAMBRWZ.PAS</code>
are set to place the components on the palette page tab named <b>Samples</b>. These can be relocated later from
the IDE if desired. </p>

<p CLASS="maroon"><a>Delphi 6 and 7</a> </p>
<p> </p>
<ol>
<li>Choose <b>File|Open...</b> from the main menu. Browse through the dialog to find
<code>FRAMEVIEWER6|7.DPK</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Open</b> and in the ensuring dialog, press <b>Compile</b> and then <b>Install</b>.
<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the searchpath. The
searchpath can be edited by choosing <b>Project|Options|Directories|Conditionals</b> from the main menu.
<p> </p></li>
<li><img SRC="import1.gif" ALIGN="top">Make sure that the Library Path string does not point to the directory of
any old HTML component files. The Library Path string can be edited from the <b>Tools|Environment</b>Options
dialog, <b>Library</b> tab.</li>
</ol>
<p> </p>

<p CLASS="maroon"><a>Delphi 2005 - 2010, XE and later</p>
<p>In the following replace <code>XXX</code> with the Delpi version name.</p>
<ol>
<li>Choose <b>File|Open...</b> from the main menu. Browse through the dialog to find
<code>FrameViewerXXX</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Project|Compile FrameViewerXXX</b> to compile <code>FrameViewerXXX.bpl</code>.
<p> </p></li>
<li>To add the components to the Tool Palette, Choose
<b>Component|Install packages</b>. Click the <b>Add..</b>. button and select<code>FrameViewerXXX.bpl</code>.
<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the searchpath. The
searchpath can be edited by choosing <b>Project|Options|Directories/Conditionals</b> from the main menu.
<p> </p></li>
<li><img SRC="import1.gif" ALIGN="top">Make sure that the Library Path string does not point to the directory of
any old HTML component files. The Library Path string can be edited from the <b>Tools|Environment</b> Options
dialog, <b>Library</b> tab.</li>
</ol>
<p> </p>

<p CLASS="maroon"><a>Lazarus 0.9 and later</a></p>
<p> </p>
<ol>
<li>Choose <b>Package|Open package file...</b> from the main menu. Browse through the dialog to find
<code>FrameViewer09.lpk</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Compile</b> in the <b>Package FrameViewer09</b> window to compile the package.<p> </p></li>
<li>Click <b>Install</b> in the <b>Package FrameViewer09</b> window to install the components.<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the
<b>Other Unit Files (-Fu)</b> searchpath. The searchpath can be edited by choosing
<b>Project|Compiler Options...</b> from the main menu.<html>
 
<style> body {font-size: 12pt; font-family: "Serif"; }</style><head>
<title></title>
<link REL="stylesheet" TYPE="text/css" HREF="demo.css"> 

</head>

<body CLASS="indent">
<p CLASS="heading"><a NAME="What">What are the HTML Viewer Components?</a></p>
<p>The HTML component set consists of the <b>THtmlViewer</b>, <b>TFrameViewer</b>, and <b>TFrameBrowser</b>
components. All three are HTML document display components:</p>


  | THtmlViewer | The basic component. THtmlViewer displays single (non-frame) documents. It also forms 	    the basis for the other two components.
-- | -- | --
  | Displays both Frame and single HTML documents. TFrameViewer is oriented more for local 	    file system use.
Also displays Frame and single HTML documents. However, TFrameBrower is oriented 	 toward Internet style protocols and URL usage. Additional code and/or components are generally required to get    data from other sources than the local file system.


<p>These components support most of the HTML 3.2 and HTML 4 specifications with some popular HTML 5 enhancements. 
Many Cascading Style Sheet properties are also supported. </p>
<ul>
<li>Cascading Stylesheets
</li>
<li>Frames
</li>
<li>Bitmap, GIF, JPEG, and PNG Images
<ul>
<li><img ALIGN="middle" ALT="Animated GIFs" HEIGHT="32" SRC="agif2.gif" WIDTH="181"></li>
<li>Transparent images
</li>
<li>Image caching
</li>
<li>Left and right floating images
</li>
<li>Image sizing attributes
</li>
<li>Client side image maps</li>
</ul></li>
<li>Large HTML files
</li>
<li>HTML Tables
</li>
<li>HTML Forms
</li>
<li>Font sizes, styles, and colors with HTML tags or default settings
</li>
<li>Background colors and images
</li>
<li>Formatted printing of the HTML document
</li>
<li>Print preview
</li>
<li>Text search
</li>
<li>Copy to clipboard
</li>
<li>Subscripts and superscripts</li>
</ul>
<p>While HTML documents are normally associated with the Internet, they are also very useful for displaying all
kinds of textual material such as documentation, helpfiles, etc. Graphics are easily incorporated in these
documents. </p>

<p CLASS="heading"><a NAME="Files">Files Supplied</a></p>
<pre>In "Demos\Compiled Framedemo"

   Demo.htm        This file
   *.htm           Frame files for Demo.htm
   FrameDem.exe    The TFrameViewer demo program
   Various image and sound files for demo

In "HtmlHelp"

   THtmlViewer.chm  Help file 
   html\*.*         Source files of help file
   images\*.*       Source files of help file
   Various html help project files

In "Source" 

   sourcecode for the THtmlViewer, TFrameViewer, and TFrameBrowser components

     HtmlView.pas, .dcr           		THtmlViewer
     FramView.pas, .dcr           		TFrameViewer
     FramBrwz.pas, .dcr           		TFrameBrowser
     BuffConv.pas
     BuffConvArrays.pas
     DitherUnit.pas
     GDIPL2A.pas
     HSLUtils.pas
     HtmlBuffer.pas
     HtmlCaches.pas
     HtmlFonts.pas
     htmlgif1.pas
     HTMLGif2.pas
     HtmlGlobals.pas
     HtmlImages.pas
     HtmlPrinter.pas
     Htmlsbs1.pas
     HTMLSubs.pas
     HtmlSymb.pas
     htmlun2.pas
     MetaFilePrinter.pas
     ReadHTML.pas
     StylePars.pas
     StyleTypes.pas
     StyleUn.pas
     URLConn.pas
     URLSubs.pas
     vwPrint.pas
     HtmlMisc.pas                        Lazarus only
     HtmlComp.lrs                        Lazarus only
     HtmlUn2.lrs                         Lazarus only
     WideStringsLcl.pas                  Lazarus only
     HTMLCompEdit.pas                    Designtime only
     FrameViewerReg.pas                  Designtime only

     FrameViewer09.lpk, .pas             Lazarus Package source file.            Recommended Lazarus Version for best HtmlViewer support >= 1.2 (Win), >= 1.4 (Linux)
     FrameViewer6.dpk, .res              Delphi 6 Package source file.           Uses TntControls for better unicode support.
     FrameViewer7.dpk, .res              Delphi 7 Package source file.           Uses TntControls for better unicode support.
     FrameViewer2005.dpk, .res           Delphi 2005 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2006.dpk, .res           Delphi 2006 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2007.dpk, .res           Delphi 2007 Package source file.        Uses TntControls for better unicode support.
     FrameViewer2009.dpk, .res           Delphi 2009 Package source file.
     FrameViewer2010.dpk, .res           Delphi 2010 Package source file.
     FrameViewerXE.dpk, .res             Delphi XE  Runtime Package source file.
     FrameViewerXE2.dpk, .res            Delphi XE2 Runtime Package source file.
     FrameViewerXE3.dpk, .res            Delphi XE3 Runtime package source file.
     FrameViewerXE4.dpk, .res            Delphi XE4 Runtime package source file.
     FrameViewerXE5.dpk, .res            Delphi XE5 Runtime package source file.
     FrameViewerXE6.dpk, .res            Delphi XE6 Runtime package source file.
     FrameViewerXE7.dpk, .res            Delphi XE7 Runtime package source file.
     FrameViewerXE8.dpk, .res            Delphi XE8 Runtime package source file.
     FrameViewerXE9.dpk, .res            Delphi XE9 Runtime package source file.
     RAD Studio 10.2\FrameViewer.dpk     Delphi 10.2 Tokyo      Runtime package source file.  
     RAD Studio 10.3\FrameViewer.dpk     Delphi 10.3 Rio        Runtime package source file.  
     RAD Studio 10.4\FrameViewer.dpk     Delphi 10.4 Sydney     Runtime package source file.  
     RAD Studio 11\FrameViewer.dpk       Delphi 11   Alexandria Runtime package source file.    
     DclFrameViewerXE.dpk, .res          Delphi XE  Designtime package source file.
     DclFrameViewerXE2.dpk, .res         Delphi XE2 Designtime package source file.
     DclFrameViewerXE3.dpk, .res         Delphi XE3 Designtime package source file.
     DclFrameViewerXE4.dpk, .res         Delphi XE4 Designtime package source file.
     DclFrameViewerXE5.dpk, .res         Delphi XE5 Designtime package source file.
     DclFrameViewerXE6.dpk, .res         Delphi XE6 Designtime package source file.
     DclFrameViewerXE7.dpk, .res         Delphi XE7 Designtime package source file.
     DclFrameViewerXE8.dpk, .res         Delphi XE8 Designtime package source file.
     DclFrameViewerXE9.dpk, .res         Delphi XE9 Designtime package source file.
     RAD Studio 10.2\dclFrameViewer.dpk  Delphi 10.2 Tokyo      Designtime package source file.  
     RAD Studio 10.3\dclFrameViewer.dpk  Delphi 10.3 Rio        Designtime package source file.  
     RAD Studio 10.4\dclFrameViewer.dpk  Delphi 10.4 Sydney     Designtime package source file.  
     RAD Studio 11\dclFrameViewer.dpk    Delphi 11   Alexandria Designtime package source file.    
     HtmlView.chm                        The help file (Sorry, but most of it is still version 9.45)
   
   Source code for the print preview dialog TBegaHtmlPrintPreviewForm

     BegaHtmlPrintPreviewForm.pas
     BegaMetaFilePrinter.pas
     BegaPreview.pas, .dfm, .lfm
     BegaPreviewForm.pas, .dfm, .lfm
     BegaPreviewPanel.pas
     BegaScrollBox.pas
     BegaZoom.pas
     ZoomAndHandCursor.RES

In "Demos\Main Demos"
     
   Source code for the demo programs

     HtmlDemo.dpr, .res                      HtmlViewer demo using TNT Unicode Controls (UTF-16)
     HtmlDemoW.dpr, .res                     HtmlViewer demo using VCL Unicode Controls (UTF-16)
     HtmlDemoLaz.lpr, .res                   HtmlViewer demo using LCL Unicode Controls (UTF-8)
     FrameDem.dpr, .res                     FrameViewer demo using TNT Unicode Controls (UTF-16)
     FrameDemW.dpr, .res                    FrameViewer demo using VCL Unicode Controls (UTF-16)
     FrameDemLaz.lpr, .res                  FrameViewer demo using LCL Unicode Controls (UTF-8)
     FrameBrowserDemoIcs.dpr, .res         FrameBrowser demo using VCL Unicode Controls and ICS 7/8 Components
     FrameBrowserDemoId10.dpr, .res        FrameBrowser demo using VCL Unicode Controls and Indy 10 Components
     AuthorizeFormUnit.pas, .dfm, .lfm
     CacheUnit.pas
     demounit.pas, .dfm, .lfm
     DownloadFormUnit.pas, .dfm, .lfm
     fbHelpIcs7.res
     fbHelpIndy10.res
     FBrDemUnit.pas, .dfm, .lfm
     FDemUnit.pas, .dfm, .lfm
     FontDlg.pas, .dfm, .lfm
     GoPage.pas, .dfm, .lfm
     Grid.res
     Htmlabt.pas, .dfm, .lfm
     ImgForm.pas, .dfm, .lfm
     InfoFormUnit.pas, .dfm, .lfm
     LogFormUnit.pas, .dfm, .lfm
     manifest.res
     OptionsId10.inc
     PrintStatusForm.pas, .dfm, .lfm
     ProxyFormUnit.pas, .dfm, .lfm
     Submit.pas, .dfm, .lfm
     SubmitTNT.pas, .dfm
     UrlConIcs.pas
     UrlConId10.pas
     UrlConVclZip.pas

In "Demos\Other Demos"     

   Some more demo projects and source files. For example the FrameBrowser demos 
     
     FrameBrowserUsingICSv7 
     FrameBrowserUsingIndy10
</pre>

<div style="age-break-inside: avoid">
<p CLASS="heading"><a NAME="InstallViewer">Installing The HTML Components</a></p>
<p>If you are installing for more than one version of Delphi, use separate directories for the installations. </p>
<p>Installation problems are almost always due to old or incorrect files being accessed. Make sure that the
Library Path or Search Path does not point to the directory of any old HTML component files. The Library Path can
be edited from the <b>Tools|Environment</b> Options dialog, <b>Library</b> tab. The Search Path from the
<b>Project|Options</b> dialog, <b>Directories/Conditionals</b> tab.</p>
</div>
<p>Delete all DCU files generated with previous installations. </p>
<p>The Register procedures in <code>HTMLVIEW.PAS</code>, <code>FRAMVIEW.PAS</code>, and <code>FRAMBRWZ.PAS</code>
are set to place the components on the palette page tab named <b>Samples</b>. These can be relocated later from
the IDE if desired. </p>

<p CLASS="maroon"><a>Delphi 6 and 7</a> </p>
<p> </p>
<ol>
<li>Choose <b>File|Open...</b> from the main menu. Browse through the dialog to find
<code>FRAMEVIEWER6|7.DPK</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Open</b> and in the ensuring dialog, press <b>Compile</b> and then <b>Install</b>.
<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the searchpath. The
searchpath can be edited by choosing <b>Project|Options|Directories|Conditionals</b> from the main menu.
<p> </p></li>
<li><img SRC="import1.gif" ALIGN="top">Make sure that the Library Path string does not point to the directory of
any old HTML component files. The Library Path string can be edited from the <b>Tools|Environment</b>Options
dialog, <b>Library</b> tab.</li>
</ol>
<p> </p>

<p CLASS="maroon"><a>Delphi 2005 - 2010, XE and later</p>
<p>In the following replace <code>XXX</code> with the Delpi version name.</p>
<ol>
<li>Choose <b>File|Open...</b> from the main menu. Browse through the dialog to find
<code>FrameViewerXXX</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Project|Compile FrameViewerXXX</b> to compile <code>FrameViewerXXX.bpl</code>.
<p> </p></li>
<li>To add the components to the Tool Palette, Choose
<b>Component|Install packages</b>. Click the <b>Add..</b>. button and select<code>FrameViewerXXX.bpl</code>.
<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the searchpath. The
searchpath can be edited by choosing <b>Project|Options|Directories/Conditionals</b> from the main menu.
<p> </p></li>
<li><img SRC="import1.gif" ALIGN="top">Make sure that the Library Path string does not point to the directory of
any old HTML component files. The Library Path string can be edited from the <b>Tools|Environment</b> Options
dialog, <b>Library</b> tab.</li>
</ol>
<p> </p>

<p CLASS="maroon"><a>Lazarus 0.9 and later</a></p>
<p> </p>
<ol>
<li>Choose <b>Package|Open package file...</b> from the main menu. Browse through the dialog to find
<code>FrameViewer09.lpk</code> (by default in the <code>\HtmlViewer\package</code> directory).
<p> </p></li>
<li>Click <b>Compile</b> in the <b>Package FrameViewer09</b> window to compile the package.<p> </p></li>
<li>Click <b>Install</b> in the <b>Package FrameViewer09</b> window to install the components.<p> </p></li>
<li>When using the HTML components, include the <code>\HtmlViewer\package</code> directory in the
<b>Other Unit Files (-Fu)</b> searchpath. The searchpath can be edited by choosing
<b>Project|Compiler Options...</b> from the main menu.

**Comment by Toolfolks** [comment]
If I open FrameViewer2011 I get on compile

[dcc32 Error] FrameViewer2010.dpk(34): E2029 'END' expected but identifier 'rrequires' found
[dcc32 Error] FrameViewer2010.dpk(84): E2029 '.' expected but end of file found

**Comment by BerndGabriel** [comment]
Welcome Newbie,

there was no Delphi 2011, thus there is no project file for it. On Delphi 2010 followed Delphi XE. 

> [dcc32 Error] FrameViewer2010.dpk(34): E2029 'END' expected but identifier 'rrequires' found 
> [dcc32 Error] FrameViewer2010.dpk(84): E2029 '.' expected but end of file found

The BDS corrupts the .dpk file under certain conditions when you edited the project. You should revert it to the orginal file.
