### ISSUE TITLE
Wow - cool thing

### ISSUE THREAD

**Issue by rbmuc** [BerndGabriel/HtmlViewer#70]
Hi there,

your htmlviewer is the perfect backoffice counterpart for webfrontends using ckeditor. 
It renders all embedded images 
img alt="" src="data:image/jpeg;base64,"...."
img alt="" src="data:image/png;base64,"...." 
img src="data:image/bmp;base64,"...." alt="" 
img src="data:image/gif;base64,"...." alt="" 

![web](https://cloud.githubusercontent.com/assets/6547586/3005698/1ce96718-ddee-11e3-94a1-cc43aafebb11.png)

But it fails on icons
img alt="" src="data:image/x-icon;base64,"...."
![win](https://cloud.githubusercontent.com/assets/6547586/3005701/57c4dfd4-ddee-11e3-9e59-ebd252d20877.png)

Would it be much work to implement them ?

rgds
Ralph

**Comment by BerndGabriel** [comment]
Hi Ralph,

did you succeed in loading icons in the meantime?

Bernd

P.S.: happy new year.
