### ISSUE TITLE
Is this project for Windows only?

### ISSUE THREAD

**Issue by vonHabsi** [BerndGabriel/HtmlViewer#81]
Is this project for Windows only?

My compilation is stopping on InitFlatSB which makes a call to `handle:=GetModuleHandle('comctrl32.dll'); `?

**Comment by BerndGabriel** [comment]
Hi, some years ago someone announced to start porting to OS/X (https://code.google.com/p/thtmlviewer/issues/detail?id=167). But there are no results (yet). I'm not aware of any other tries. 

Thus HtmlViewer is still a "Windows only" project. :(

**Comment by BerndGabriel** [comment]
Branch "HtmlViewer-11.6-to-11.7" now compiles and runs a basic HtmlViewer and Linux/GTK2!

**Comment by sunsell** [comment]
handle:=GetModuleHandle('comctrl32.dll');      ???

**Comment by BerndGabriel** [comment]
That's not for Linux, of course!
Hm, the non-windows settings in htmlcons.inc got lost.
Commit e68efc889578c7cbc36651d4afd6f56d73cfdaef restores them.

**Comment by sunsell** [comment]
I add a THtmlViewer on a form.
Lazarus hangs.

HtmlViewer-11.6-to-11.7, current.
i386 ubuntu 14.04 with updates
fpc 2.6.4  Lazarus 1.4.2  http://michael-ep3.physik.uni-halle.de/Lazarus/releases/Lazarus%20Linux%20i386%20DEB/Lazarus%201.4.2/

**Comment by ak545** [comment]
Hello, BerndGabriel!
--------
Fedora 23 Mate x86_64
fpc-3.0.0-1.x86_64.rpm
fpc-src-3.0.0-151202.x86_64.rpm
lazarus-1.6-0.x86_64.rpm
HtmlViewer-11.6-to-11.7, current. Compiled and install successful.
But, when I added a THtmlViewer on a TForm Lazarus is hangs (Error ready...).
--------
Windows 10 64-bit + lazarus-1.6.0-fpc-3.0.0-win64 all work correct.
--------

**Comment by sunsell** [comment]
Thank you. Now it works.

**Comment by ak545** [comment]
Fedora 23 Mate x86_64
fpc-3.0.0-1.x86_64.rpm
fpc-src-3.0.0-151202.x86_64.rpm
lazarus-1.6-0.x86_64.rpm
HtmlViewer-11.6-to-11.7, current.

Yes, now it's work!

**BerndGabriel**, thank a lot!

**Comment by sunsell** [comment]
Other error.

Compile Project, Target: project1: Exit code 1, Errors: 1, Hints: 1
unit1.pas(18,32) Error: Duplicate identifier "Color"
unit1.pas(18,32) Hint: Identifier already defined in unit FORMS at line 745

type

  { TForm1 }

  TForm1 = class(TForm)
    HtmlViewer1: THtmlViewer;
    procedure HtmlViewer1BitmapRequest(Sender: TObject; const SRC: ThtString;
      var Bitmap: TBitmap; var **Color**: TColor);

**Comment by BerndGabriel** [comment]
Please use {$mode delphi} instead of {$mode objfpc}.

**Comment by sunsell** [comment]
Thanks a lot!
