### ISSUE TITLE
Free on an Freed Object

### ISSUE THREAD

**Issue by landrix** [BerndGabriel/HtmlViewer#82]
after this call

mfp := TMetaFilePrinter.Create(self);
html.PrintPreview(mfp);

the application crash.

i located the problem at

procedure ThtDocument.Clear;
...  inherited Clear;  //(self.Count = 1)
and 
procedure TFreeList.Notify(Ptr: Pointer; Action: TListNotification);

as a workarround, this helps:

procedure TFreeList.Notify(Ptr: Pointer; Action: TListNotification);
begin
  if (Action = lnDeleted) and FOwnsObjects then
  if TObject(Ptr).ClassName <> 'TFreedObject' then
    TObject(Ptr).Free;
end;

**Comment by lainz** [comment]
Confirmed. I have this problem when I use:
HtmlViewer1.Print();
Under Lazarus 1.2.6 FPC 2.6.4

The problem is in
ThtDocument.Clear
... inherited Clear;

This do the print but the program crashes

I've tried your workaround and doesn't works for me, the application just crashes

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue.

**Comment by landrix** [comment]
The error throws in PrintList.Free;

function THtmlViewer.Print(Prn: ThtPrinter; FromPage: Integer; ToPage: Integer; Mode: ThtPrintPreviewMode): Integer;
  ...
  PrintList := ThtDocument.CreateCopy(SectionList);
  try
  ...
  finally
    PrintList.Free;
  end;  
  ...

i changed this and it helps - no memory leak is produced:

procedure ThtDocument.Clear;
begin
  ...
  if not IsCopy then
    inherited Clear;
  ...
end;

**Comment by BerndGabriel** [comment]
commit 68484f230cbaafdc56295a707309f671fe10fa21 fixes this issue.

The issue was induced by adding TSections twice.
