### ISSUE TITLE
Print Preview Error

### ISSUE THREAD

**Issue by fevzialis** [BerndGabriel/HtmlViewer#83]
Reported by fevzi.al...@gmail.com, Mar 13, 2015 
Which steps will reproduce the problem?
1. locate "HtmlViewer\Demos\Main Demos"
2. open "HtmlDemoW.dpr" and run
3. press F3 or "File > Open" click and load attached 28983001As_Data.htm files or other html files
4. File > Print Preview... click

What is the expected output? What do you see instead?
The printout should arrive, "Invalid Pointer Operation" Error

Which version of the product are you using? Which compiler version are you
using? On which operating system?
w8.1 - xe3 - THtmlViewer-115-r472

Please attach test html files and screenshots, if appropriate.
Please provide any additional information:

excuse me, i have bad english ...

example file:
https://thtmlviewer.googlecode.com/issues/attachment?aid=4050000000&name=Invalid+Pointer+Op+Metarials.zip&token=ABZ6GAflMhcYNEnSIPYqcmB2CPfYE46eTw%3A1428022673283

**Comment by BerndGabriel** [comment]
Thanks for spotting this issue. Confirmed.

**Comment by BerndGabriel** [comment]
commit 68484f230cbaafdc56295a707309f671fe10fa21 fixes this issue.

The issue was induced by adding TSections twice.
