### ISSUE TITLE
Example of using IDDisplay property was broken (see whatsnew.html, version 8.25)

### ISSUE THREAD

**Issue by kazalex** [BerndGabriel/HtmlViewer#96]

**Comment by BerndGabriel** [comment]
Looks like it is OK in compiled FrameDem.exe 11.6

**Comment by kazalex** [comment]
![9_44_vs_11_6](https://cloud.githubusercontent.com/assets/11914374/8846499/cb8c325c-3138-11e5-95f4-37f5b34b77d6.png)

**Comment by BerndGabriel** [comment]
Thanks for clarification. I got it at last.

**Comment by BerndGabriel** [comment]
commit 49034aee2b024eb297c05fdbb35c29a3dd20629d fixes this issue. 

Actually the example was an incorrectly formed list item and the old demo app obviously ignored the &lt;/li&gt;s
